#!/usr/bin/env bash
# Xremap launcher on Fedora

# cat /sys/devices/virtual/dmi/id/product_name

. /etc/os-release
if [[ "${VARIANT_ID}" == "workstation" ]]; then
    VARIANT_ID="gnome"
fi

host_specific_config="$HOME/.config/xremap/$(hostnamectl hostname)-${VARIANT_ID}.yml"

if [ -f "$host_specific_config" ]; then
    ~/.local/bin/xremap "$host_specific_config" ~/.config/xremap/config.yml
else
    ~/.local/bin/xremap ~/.config/xremap/config.yml
fi
