#!/usr/bin/env bash
# ~/.config/sway/sway-tmux.sh
# Switch freely between tmux panes and sway containers
# @depends: dunst, jq

echo "$$ sway-tmux: ---------- $(date +"%Y-%m-%d %T.%6N") ----------" >>/tmp/xreaker.log

# arrows="left | down | up | right"
# if ! echo "| $arrows |" | grep -F -q "| $1 |"; then
#     notify-send "sway-tmux: argument must be one of \"$arrows\""
#     exit 1
# fi

arrow="$1"
at_arrow_cmd=
tmux_cmd=
sway_cmd=

case "$arrow" in
left)
    at_arrow_cmd="tmux display-message -p '#{pane_at_left}'"
    tmux_cmd="tmux select-pane -L"
    sway_cmd="swaymsg focus left"
    ;;
down)
    at_arrow_cmd="tmux display-message -p '#{pane_at_bottom}'"
    tmux_cmd="tmux select-pane -D"
    sway_cmd="swaymsg focus down"
    ;;
up)
    at_arrow_cmd="tmux display-message -p '#{pane_at_top}'"
    tmux_cmd="tmux select-pane -U"
    sway_cmd="swaymsg focus up"
    ;;
right)
    at_arrow_cmd="tmux display-message -p '#{pane_at_right}'"
    tmux_cmd="tmux select-pane -R"
    sway_cmd="swaymsg focus right"
    ;;
*)
    notify-send "sway-tmux: argument must be one of \"left | down | up | right\""
    exit 1
    ;;
esac

# swaymsg -t get_tree -r | jq '.. | select(.type?) | select(.focused==true) | {name, app_id, id, pid}'
focused_app_id=$(swaymsg -t get_tree -r | jq -r '.. | select(.type?) | select(.focused==true) | .app_id')
echo "$$ sway-tmux: sway focused_app_id: $focused_app_id, tmux list-panes count: $(tmux list-panes | wc -l)" >>/tmp/xreaker.log

if [ "$focused_app_id" == "Alacritty" ] && [[ "$(tmux list-panes | wc -l)" -gt "1" ]]; then
    at_arrow=$(eval "$at_arrow_cmd")
    echo "$$ sway-tmux: at_arrow: $at_arrow" >>/tmp/xreaker.log
    if [[ "$at_arrow" == "0" ]]; then
        echo "$$ sway-tmux: switch tmux pane" >>/tmp/xreaker.log
        ret=$(eval "$tmux_cmd")
        exit "$ret"
    fi
fi

echo "$$ sway-tmux: switch sway container" >>/tmp/xreaker.log
ret=$(eval "$sway_cmd")
exit "$ret"
