---

- name: Check if shadowsocks-rust is installed
  ansible.builtin.stat:
    path: "~/.cargo/bin/ssservice"
  register: services_ss_check

- name: Install shadowsocks-rust
  ansible.builtin.command: "~/.cargo/bin/cargo install shadowsocks-rust"
  changed_when: false
  when: not services_ss_check.stat.exists
  notify: Start and enable shadowsocks-rust-local service
