---

# Install xremap config

- name: Install xremap/config.yml (chromebook link)
  when: ansible_product_name == 'Link'
  ansible.builtin.copy:
    src: files/xremap-link.yml
    dest: ~/.config/xremap/config.yml
    mode: "0644"

- name: Install xremap/config.yml
  when: ansible_product_name != 'Link'
  ansible.builtin.copy:
    src: files/xremap.yml
    dest: ~/.config/xremap/config.yml
    mode: "0644"

# Running xremap without sudo

# https://github.com/k0kubun/xremap#running-xremap-without-sudo
# https://discussion.fedoraproject.org/t/fedora-38-dleyna-renderer-connector-dbus-not-found/81257
- name: Check if /etc/udev/rules.d/input.rules exists
  ansible.builtin.stat:
    path: "/etc/udev/rules.d/input.rules"
  register: services_input_rules_check

- name: Running xremap without sudo (+uaccess)
  when: not services_input_rules_check.stat.exists
  ansible.builtin.shell: |
    set -o pipefail
    sudo gpasswd -a $USER input
    echo 'KERNEL=="uinput", MODE="0660", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules

    sudo dnf install dleyna-connector-dbus
  changed_when: false

# Install and start xremap service
# https://github.com/ueaner/dotfiles/blob/main/.config/systemd/user/xremap.service
# https://github.com/ueaner/dotfiles/tree/main/.config/autostart/xremap.desktop

- name: Check if xremap is installed
  ansible.builtin.stat:
    path: "~/.cargo/bin/xremap"
  register: services_xremap_check

- name: Install xremap (GNOME Wayland)
  when:
    - not services_xremap_check.stat.exists
    - desktop_name == "gnome"
  ansible.builtin.command: "~/.cargo/bin/cargo install xremap --features gnome"
  changed_when: false
  notify: Start xremap service

- name: Install xremap (Sway)
  when:
    - not services_xremap_check.stat.exists
    - desktop_name == "sway"
  ansible.builtin.command: "~/.cargo/bin/cargo install xremap --features sway"
  changed_when: false
  notify: Start xremap service
