---

- name: Check if xremap is installed
  ansible.builtin.stat:
    path: "~/.cargo/bin/xremap"
  register: xremap_check

- name: Install xremap/config.yml (chromebook link)
  when: ansible_product_name == 'Link'
  ansible.builtin.copy:
    src: files/xremap-link.yml
    dest: ~/.config/xremap/config.yml
    mode: "0644"

- name: Install xremap/config.yml
  when: ansible_product_name != 'Link'
  ansible.builtin.copy:
    src: files/xremap.yml
    dest: ~/.config/xremap/config.yml
    mode: "0644"

- name: Install xremap (GNOME Wayland)
  when:
    - not xremap_check.stat.exists
    - desktop_name == "gnome"
  ansible.builtin.command: "~/.cargo/bin/cargo install xremap --features gnome"
  changed_when: false
  notify: Start and enable xremap service

- name: Install xremap (Sway)
  when:
    - not xremap_check.stat.exists
    - desktop_name == "sway"
  ansible.builtin.command: "~/.cargo/bin/cargo install xremap --features sway"
  changed_when: false
  notify: Start and enable xremap service
