# ~/.config/neovide/config.toml

# For Linux, use `Noto Sans Mono CJK SC` font provided by `google-noto-sans-mono-cjk-vf-fonts`
# fc-list | grep 'Noto Sans Mono CJK SC'

[font]
size = 13

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"
