---
- name: Install frpc (local)
  install-package:
    name: frpc
    placeholders:
      repo: fatedier/frp
      version: "{{ template.github.version_v }}"
    template: "{{ template.github.archive_v }}"
    archives:
      # The requested version number is "v0.64.0", but the archive name uses "0.64.0" without the "v".
      # https://github.com/fatedier/frp/releases/download/v0.64.0/frp_0.64.0_linux_amd64.tar.gz
      - frp_<version>_linux_amd64.tar.gz
      - frp_<version>_linux_arm64.tar.gz
      - frp_<version>_darwin_amd64.tar.gz
      - frp_<version>_darwin_arm64.tar.gz
    dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
    strip: 1
    include:
      # frp_0.64.0_linux_amd64/frpc
      - frpc
    # launchctl list | grep frpc
    # launchctl list org.gofrp.frpc
    # launchctl print gui/501/org.gofrp.frpc | awk '/state =/ { print $3 }'
    postinstall: |-
      frpc --version
      if [[ $(uname -s) == 'Linux' ]]; then
          systemctl --user enable --now frpc
          exit $?
      fi

      if [[ -f ~/.local/bin/frpc ]]; then
          ln -sf ~/.local/bin/frpc /opt/local/bin/frpc
      fi
      if [[ -f ~/.local/etc/frpc-mac15.toml ]]; then
          ln -sf ~/.local/etc/frpc-mac15.toml /opt/local/etc/frpc-mac15.toml
      fi
      if [[ -f ~/.config/plist/LaunchAgents/org.gofrp.frpc.plist ]]; then
          ln -sf ~/.config/plist/LaunchAgents/org.gofrp.frpc.plist ~/Library/LaunchAgents/org.gofrp.frpc.plist
      fi

      if [[ -f ~/Library/LaunchAgents/org.gofrp.frpc.plist ]]; then
          if launchctl print gui/$(id -u)/org.gofrp.frpc >/dev/null 2>&1; then
              launchctl unload ~/Library/LaunchAgents/org.gofrp.frpc.plist
          fi
          launchctl load ~/Library/LaunchAgents/org.gofrp.frpc.plist
      fi
  tags:
    - frpc
