---

- name: Install/Upgrade shadowsocks (local)
  ansible.builtin.include_tasks: shadowsocks.yml
  tags:
    - upgrade
    - sslocal

- name: Install/Upgrade caddy
  ansible.builtin.include_tasks: caddy.yml
  tags:
    - upgrade
    - caddy

- name: Install/Upgrade lima
  ansible.builtin.include_tasks: lima.yml
  tags:
    - upgrade
    - lima

- name: Install/Upgrade llama
  ansible.builtin.include_tasks: llama.yml
  tags:
    - upgrade
    - llama
