---

- name: Install/Upgrade shadowsocks-rust (local) for Linux
  when: ansible_system == "Linux"
  ansible.builtin.unarchive:
    src: "{{ archives_server }}/shadowsocks-linux-x86_64.tar.xz"
    dest: "~/.local/bin/"
  notify: Start and enable shadowsocks-rust-local service
  tags:
    - install
    - sslocal

- name: Install/Upgrade shadowsocks-rust (local) for macOS
  when: ansible_system == "Darwin"
  ansible.builtin.unarchive:
    src: "{{ archives_server }}/shadowsocks-darwin-x86_64.tar.xz"
    dest: "~/.local/bin/"
  notify: Start and enable shadowsocks-rust-local service
  tags:
    - install
    - sslocal
