---

- name: Install shadowsocks-rust (local)
  install-package:
    name: shadowsocks-rust
    placeholders:
      repo: shadowsocks/shadowsocks-rust
      version: "{{ template.github.version }}"
    template: "{{ template.github.archive }}"
    archives:
      # https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.23.5/shadowsocks-v1.23.5.x86_64-unknown-linux-gnu.tar.xz
      - shadowsocks-<version>.x86_64-unknown-linux-gnu.tar.xz
      - shadowsocks-<version>.aarch64-unknown-linux-gnu.tar.xz
      - shadowsocks-<version>.x86_64-apple-darwin.tar.xz
      - shadowsocks-<version>.aarch64-apple-darwin.tar.xz
    include:
      - sslocal
      - ssmanager
      - ssserver
      - ssservice
      - ssurl
    dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
    # launchctl list | grep shadowsocks
    # launchctl list org.shadowsocks.shadowsocks-rust
    # launchctl print gui/501/org.shadowsocks.shadowsocks-rust | awk '/state =/ { print $3 }'
    postinstall: |-
      sslocal --version
      if [[ $(uname -s) == 'Linux' ]]; then
          systemctl --user enable --now shadowsocks-rust-local
          exit $?
      fi

      if [[ -x ~/.local/bin/sslocal ]]; then
          ln -sf ~/.local/bin/sslocal /opt/local/bin/sslocal
          ln -sf ~/.local/bin/ssservice /opt/local/bin/ssservice
      fi
      if [[ -f ~/.local/etc/shadowsocks-rust-local.json ]]; then
          ln -sf ~/.local/etc/shadowsocks-rust-local.json /opt/local/etc/shadowsocks-rust-local.json
          ln -sf ~/.local/etc/shadowsocks-rust-local.acl /opt/local/etc/shadowsocks-rust-local.acl
      fi
      # https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/org.shadowsocks.shadowsocks-rust.plist
      if [[ -f ~/.config/plist/LaunchAgents/org.shadowsocks.shadowsocks-rust.plist ]]; then
          ln -sf ~/.config/plist/LaunchAgents/org.shadowsocks.shadowsocks-rust.plist ~/Library/LaunchAgents/org.shadowsocks.shadowsocks-rust.plist
      fi

      if [[ -f ~/Library/LaunchAgents/org.shadowsocks.shadowsocks-rust.plist ]]; then
          if launchctl print gui/$(id -u)/org.shadowsocks.shadowsocks-rust >/dev/null 2>&1; then
              launchctl unload ~/Library/LaunchAgents/org.shadowsocks.shadowsocks-rust.plist
          fi
          launchctl load ~/Library/LaunchAgents/org.shadowsocks.shadowsocks-rust.plist
      fi
  tags:
    - shadowsocks
