---

# Server Only

- name: Install nginx proxy
  when: ansible_distribution == "CentOS"
  delegate_to: sp
  tags:
    - upgrade
    - ssproxy
  block:
    - name: Welcome to {{ ansible_distribution }}
      ansible.builtin.debug:
        msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Check if nginx is installed
      ansible.builtin.stat:
        path: "/usr/sbin/nginx"
      register: server_nginx_check

    - name: Install nginx
      become: true
      ansible.builtin.dnf:
        name:
          - nginx
          - nginx-mod-stream

    - name: Install nginx.conf file
      ansible.builtin.copy:
        src: ~/.local/etc/ss-nginx-proxy.conf
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Start and enable nginx
