# https://alacritty.org/config-alacritty.html
live_config_reload = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 2
y = 1

[cursor.style]
shape = "Beam"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1e2030"
foreground = "#eaeaea"

# Named ANSI colors [0-7]
[colors.normal]
black   = "#1e2030"
red     = "#df6566"
green   = "#c5d15c"
yellow  = "#ecce58"
blue    = "#8cb6e1"
magenta = "#cfabe0"
cyan    = "#81cabf"
white   = "#eaeaea"

# Named ANSI colors [8-15]
[colors.bright]
black   = "#778899"
red     = "#df6566"
green   = "#c5d15c"
yellow  = "#ecce58"
blue    = "#8cb6e1"
magenta = "#cfabe0"
cyan    = "#81cabf"
white   = "#eaeaea"

[font]
# Alacritty.desktop: Exec=alacritty --option font.size=9.0
# alacritty msg config font.size=9.0
size = 9.0  # Linux: 9.0, macOS: 12.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 5

[keyboard]
bindings = [
    { key = "C",           mods = "Super",         action = "Copy"             },
    { key = "V",           mods = "Super",         action = "Paste"            },
    { key = "H",           mods = "Super",         action = "Hide"             },
    { key = "Q",           mods = "Super",         action = "Quit"             },
    { key = "F",           mods = "Super|Control", action = "ToggleFullscreen" },
    { key = "Key0",        mods = "Super",         action = "ResetFontSize"    },
    { key = "Equals",      mods = "Super",         action = "IncreaseFontSize" },
    { key = "Minus",       mods = "Super",         action = "DecreaseFontSize" },

    # >>> tmux shortcuts: prefix A-s \u001Bs
    # Use tmux as a normal application, `tmux session` as `window`, and `tmux window` as `tab`
    { key = "R",           mods = "Super",         chars = "\u001Bsr"          }, # reload config
    { key = "R",           mods = "Super|Shift",   chars = "\u001BsR"          }, # refresh screen
    { key = "D",           mods = "Super",         chars = "\u001Bsd"          }, # detach current client
    { key = "N",           mods = "Super",         chars = "\u001BsC"          }, # new session
    { key = "T",           mods = "Super",         chars = "\u001Bsc"          }, # new window
    { key = "W",           mods = "Super",         chars = "\u001BsX"          }, # close window
    { key = "Tab",         mods = "Control",       chars = "\u001Bs."          }, # next window
    { key = "Tab",         mods = "Control|Shift", chars = "\u001Bs,"          }, # previous window
    { key = "Period",      mods = "Super",         chars = "\u001Bs."          }, # Super + . next window
    { key = "Comma",       mods = "Super",         chars = "\u001Bs,"          }, # Super + , previous window, Preferences on macOS
    # https://github.com/rust-windowing/winit/issues/600 Shift Keycode None
    { key = "Backslash",   mods = "Super",         chars = "\u001Bs\\"         }, # Super + \ vertical split
    { key = 43,            mods = "Super|Shift",   chars = "\u001Bs|"          }, # Super + | horizontal split, pipe, on Linux
    { key = "E",           mods = "Super",         chars = "\u001Bse"          }, # choose tree / pane explorer
    { key = "Z",           mods = "Super",         chars = "\u001Bsz"          }, # pane zoom
    { key = "Semicolon",   mods = "Super",         chars = "\u001Bs:"          }, # Super + ; command mode
    { key = "Escape",      mods = "Super",         chars = "\u001Bs\u001B"     }, # vi-mode
    { key = "F",           mods = "Super",         chars = "\u001Bs/"          }, # search
    { key = "S",           mods = "Super|Shift",   chars = "\u001BsS"          }, # synchronize panes toggle
    # <<< tmux shortcuts: prefix A-s \u001Bs

    # fixed: CTRL-Q needs to be pressed twice to register in macOS
    # https://github.com/alacritty/alacritty/issues/1359
    { key = "Q",           mods = "Control",       chars = "\u0011"            },
    # https://github.com/alacritty/alacritty/issues/3014
    { key = "Slash",       mods = "Control",       chars = "\u001F"            }
]
