# vim: set filetype=yaml:
# Copy this to ~/.config/xremap/config.yml
# Reference：https://github.com/alacritty/alacritty/blob/master/alacritty.yml

---
# yamllint disable rule:commas rule:braces rule:colons rule:line-length

live_config_reload: true

# 0.10+
window:
  # 有透明度可以看到桌面背景，同时透明度会影响最终背景色的渲染效果
  opacity: 1.0
  dynamic_padding: true
  padding:
    x: 2
    y: 1

  # "fixed" GNOME Wayland 边框问题
  decorations: none

cursor:
  style:
    shape: Beam

env:
  TERM: xterm-256color

  # ZDOTDIR: ~/.config/zsh
  # XDG_CONFIG_HOME: ~/.config
  # XDG_CACHE_HOME: ~/.cache
  # XDG_DATA_HOME: ~/.local/share
  # XDG_STATE_HOME: ~/.local/state
  # XDG_BIN_HOME: ~/.local/bin
  # XDG_LIB_HOME: ~/.local/lib
  # XDG_RUNTIME_DIR: ~/.local/runtime

font:
  # Alacritty.desktop: Exec=alacritty --option font.size=9.0
  # alacritty msg config font.size=9.0
  size: 12.0  # Linux: 9.0, macOS: 12.0
  offset:
    x: 0
    y: 5
  normal:
    family: SauceCodePro Nerd Font
    style: Regular
  bold:
    family: SauceCodePro Nerd Font
    style: Bold
  italic:
    family: SauceCodePro Nerd Font
    style: Italic
  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

selection:
  # 保存到系统剪切板
  save_to_clipboard: true

# https://github.com/alacritty/alacritty/pull/1856#issuecomment-444581656
# Linux 下在 session login 时使用 login shell, 打开终端时使用 non-login shell, 对于 .zprofile 的变更需要重新登录
# macOS 下登陆时不处理 login shell, 打开终端时自动使用 login shell, 对于 .zprofile 的变更只需要重新打开终端
# shell:
#   # alacritty 作为交互终端使用 login 模式，会加载 ~/.zprofile 环境变量配置文件
#   # tmux 会继承 alacritty 终端已有环境变量，使用 non-login 模式，避免重复加载环境变量
#   # alacritty 可以为 shell 设置环境变量，但是 alacritty 自身不支持读取环境变量
#   program: /usr/bin/login
#   args: [ "-pf", "ueaner" ]

# import:
#   - ~/.config/alacritty/colors.yml
#   - ~/.config/alacritty/key_bindings.yml

# ----------------------------------------------------------------
# colors
# ----------------------------------------------------------------
# 0x 开头或者 # 开头都可
# primary.background 和 normal.black 使用同色
theme: Tomorrow-Night-Bright
draw_bold_text_with_bright_colors: true

# Named ANSI colors, shell 中使用相应的颜色名称会使用以下颜色值，如:
#   - zsh prompt colors
#   - tmux STYLES
#   - fzf --ansi
# Vim 看起来实际读取的值不是终端设置的值，应该是内部写死的。
colors:
  # Default colors
  primary:
    # background: "#181a1f"
    # background: "#1e222a"
    background: "#1e2030"
    foreground: "#eaeaea"

  # Normal colors, ANSI [0-7]
  normal:
    black:   "#1e2030"
    red:     "#df6566"
    green:   "#c5d15c"
    yellow:  "#ecce58"
    blue:    "#8cb6e1"
    magenta: "#cfabe0"
    cyan:    "#81cabf"
    white:   "#eaeaea"

  # Bright colors, ANSI [8-15]
  bright:
    black:   "#778899"  # gray, grey
    red:     "#df6566"
    green:   "#c5d15c"
    yellow:  "#ecce58"
    blue:    "#8cb6e1"
    magenta: "#cfabe0"
    cyan:    "#81cabf"
    white:   "#eaeaea"

# ----------------------------------------------------------------
# key bindings
# ----------------------------------------------------------------
key_bindings:
  - { key: C,          mods: Super,         action: Copy             }
  - { key: V,          mods: Super,         action: Paste            }
  - { key: H,          mods: Super,         action: Hide             }
  - { key: Q,          mods: Super,         action: Quit             }
  - { key: F,          mods: Super|Control, action: ToggleFullscreen }
  - { key: Key0,       mods: Super,         action: ResetFontSize    }
  - { key: Equals,     mods: Super,         action: IncreaseFontSize }
  - { key: Minus,      mods: Super,         action: DecreaseFontSize }

  # >>> tmux shortcuts: prefix A-s \x1b\x73
  # Use tmux as a normal application, `tmux session` as `window`, and `tmux window` as `tab`
  - { key: R,          mods: Super,         chars: "\x1b\x73\x72" }  # reload config
  - { key: R,          mods: Super|Shift,   chars: "\x1b\x73\x52" }  # refresh screen
  - { key: D,          mods: Super,         chars: "\x1b\x73\x64" }  # detach current client
  - { key: N,          mods: Super,         chars: "\x1b\x73\x43" }  # new session
  - { key: T,          mods: Super,         chars: "\x1b\x73\x63" }  # new window
  - { key: W,          mods: Super,         chars: "\x1b\x73\x58" }  # close window
  - { key: Tab,        mods: Control,       chars: "\x1b\x73\x2e" }  # next window
  - { key: Tab,        mods: Control|Shift, chars: "\x1b\x73\x2c" }  # previous window
  - { key: Period,     mods: Super,         chars: "\x1b\x73\x2e" }  # Super + . next window
  - { key: Comma,      mods: Super,         chars: "\x1b\x73\x2c" }  # Super + , previous window, Preferences on macOS
  # https://github.com/rust-windowing/winit/issues/600 Shift Keycode None
  - { key: Backslash,  mods: Super,         chars: "\x1b\x73\x5c" }  # Super + \ vertical split
  - { key: Backslash,  mods: Super|Shift,   chars: "\x1b\x73\x7c" }  # Super + | horizontal split, pipe, on macOS
  - { key: E,          mods: Super,         chars: "\x1b\x73\x65" }  # choose tree / pane explorer
  - { key: Z,          mods: Super,         chars: "\x1b\x73\x7a" }  # pane zoom
  - { key: Semicolon,  mods: Super,         chars: "\x1b\x73\x3a" }  # Super + ; command mode
  - { key: Escape,     mods: Super,         chars: "\x1b\x73\x1b" }  # vi-mode
  - { key: F,          mods: Super,         chars: "\x1b\x73\x2f" }  # search
  - { key: S,          mods: Super|Shift,   chars: "\x1b\x73\x53" }  # synchronize panes toggle
  # <<< tmux shortcuts: prefix A-s \x1b\x73

  # fixed: CTRL-Q needs to be pressed twice to register in macOS
  # https://github.com/alacritty/alacritty/issues/1359
  - { key: Q,          mods: Control,       chars: "\x11" }
  # https://github.com/alacritty/alacritty/issues/3014
  - { key: Slash,      mods: Control,       chars: "\x1f" }
