---

- name: Install drawio latest
  when: ansible_pkg_mgr == "dnf"
  ansible.builtin.shell: |
    set -o pipefail
    URL=$(curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | grep browser_download_url | grep '\.rpm' | cut -d '"' -f 4)
    sudo dnf install "https://mirror.ghproxy.com/$URL"
  changed_when: false
  tags:
    - upgrade
    - drawio
