---

- name: Install basic tools (dnf)
  when: ansible_pkg_mgr == "dnf"
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    name: "{{ tools.dnf }}"
  notify: Modify flathub remote repository to sjtu

- name: Install go tools
  ansible.builtin.command: ~/go/bin/go install -v {{ item }}
  changed_when: false
  loop: "{{ tools.go }}"
  environment:
    GO111MODULE: "on"
    GOPROXY: https://goproxy.cn,https://goproxy.io,direct

- name: Install rust tools
  ansible.builtin.command: "~/.cargo/bin/cargo install {{ item }}"
  changed_when: false
  loop: "{{ tools.rust }}"

- name: Install python tools
  ansible.builtin.command: "~/.local/bin/pip3 install --user {{ item }}"
  changed_when: false
  loop: "{{ tools.python }}"
  environment:
    PYTHONUSERBASE: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local"
