---

# `dnf update` in `system role`
- name: Install basic tools (dnf)
  when: ansible_pkg_mgr == "dnf"
  become: true
  ansible.builtin.dnf:
    name: "{{ tools.dnf }}"
  notify: Modify flathub remote repository to sjtu

- name: Install gui tools (flatpak)
  community.general.flatpak:
    name: "{{ tools.flatpak }}"
    method: user
  notify:
    - Native Wayland for Chrome

- name: Upgrade gui tools (flatpak)
  ansible.builtin.command: flatpak --user update -y
  changed_when: false
  tags:
    - upgrade
    - gui

- name: Install/Upgrade go tools
  ansible.builtin.command: ~/go/bin/go install -v {{ item }}
  changed_when: false
  loop: "{{ tools.go }}"
  environment:
    GO111MODULE: "on"
    GOPROXY: https://goproxy.cn,https://goproxy.io,direct
  tags:
    - upgrade
    - go

- name: Install/Upgrade rust tools
  ansible.builtin.command: "~/.cargo/bin/cargo install {{ item }}"
  changed_when: false
  loop: "{{ tools.rust }}"
  tags:
    - upgrade
    - rust

- name: Install/Upgrade python tools
  ansible.builtin.command: "~/.local/bin/pip3 install --upgrade --user {{ item }}"
  changed_when: false
  loop: "{{ tools.python }}"
  environment:
    PYTHONUSERBASE: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local"
  tags:
    - upgrade
    - python

- name: Install/Upgrade node.js tools
  ansible.builtin.command: ~/.local/share/fnm/aliases/default/bin/pnpm install -g {{ item }}
  changed_when: false
  loop: "{{ tools.node }}"
  tags:
    - upgrade
    - node

- name: Install/Upgrade neovim (include_tasks)
  ansible.builtin.include_tasks: neovim.yml
  tags:
    - upgrade
    - neovim
    - neovide

- name: Install drawio (include_tasks)
  ansible.builtin.include_tasks: drawio.yml
  tags:
    - upgrade
    - drawio

- name: Install zk (include_tasks)
  ansible.builtin.include_tasks: zk.yml
  tags:
    - upgrade
    - zk

- name: Install plantuml.jar (include_tasks)
  ansible.builtin.include_tasks: plantuml.yml
  tags:
    - upgrade
    - plantuml

- name: Install wasm (include_tasks)
  ansible.builtin.include_tasks: wasm.yml
  tags:
    - wasm
