---

# `dnf update` in `system role`
- name: Install basic tools (dnf)
  when: ansible_pkg_mgr == "dnf"
  become: true
  ansible.builtin.dnf:
    name: "{{ tools.dnf }}"
  notify: Modify flathub remote repository to sjtu

- name: Install gui tools (flatpak)
  community.general.flatpak:
    name: "{{ tools.flatpak }}"
    method: user
  notify:
    - Native Wayland for Chrome

- name: Upgrade gui tools (flatpak)
  ansible.builtin.command: flatpak --user update -y
  changed_when: false
  tags:
    - upgrade

- name: Install/Upgrade go tools
  ansible.builtin.command: ~/go/bin/go install -v {{ item }}
  changed_when: false
  loop: "{{ tools.go }}"
  environment:
    GO111MODULE: "on"
    GOPROXY: https://goproxy.cn,https://goproxy.io,direct
  tags:
    - upgrade

- name: Install/Upgrade rust tools
  ansible.builtin.command: "~/.cargo/bin/cargo install {{ item }}"
  changed_when: false
  loop: "{{ tools.rust }}"
  tags:
    - upgrade

- name: Install/Upgrade python tools
  ansible.builtin.command: "~/.local/bin/pip3 install --upgrade --user {{ item }}"
  changed_when: false
  loop: "{{ tools.python }}"
  environment:
    PYTHONUSERBASE: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local"
  tags:
    - upgrade

- name: Install/Upgrade node.js tools
  ansible.builtin.command: ~/.local/share/fnm/aliases/default/bin/pnpm install -g {{ item }}
  changed_when: false
  loop: "{{ tools.node }}"
  tags:
    - upgrade

- name: Install neovim (include_tasks)
  ansible.builtin.include_tasks: neovim.yml
  tags:
    - upgrade

- name: Install drawio (include_tasks)
  ansible.builtin.include_tasks: drawio.yml
  tags:
    - upgrade
