- name: install basic tools (dnf)
  when: ansible_pkg_mgr == "dnf"
  become: true
  become_method: sudo
  dnf:
    name: "{{ tools.dnf }}"

- name: install go tools
  shell: ~/go/bin/go install -v {{ item }}
  loop: "{{ tools.go }}"
  environment:
    GO111MODULE: "on"
    GOPROXY: https://goproxy.cn,https://goproxy.io,direct

- name: install rust tools
  shell: "~/.cargo/bin/cargo install {{ item }}"
  loop: "{{ tools.rust }}"

- name: install python tools
  shell: "~/.local/bin/pip3 install --user {{ item }}"
  loop: "{{ tools.python }}"
  environment:
    PYTHONUSERBASE: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local"
