---

- name: Install neovide
  ansible.builtin.unarchive:
    src: https://ghproxy.com/https://github.com/neovide/neovide/releases/download/{{ versions.neovide }}/neovide.tar.gz
    dest: "~/.cargo/bin/"
    remote_src: true
  changed_when: false

- name: Install neovide.desktop
  ansible.builtin.copy:
    src: files/neovide.desktop
    dest: ~/.local/share/applications/neovide.desktop
    mode: "0644"

- name: Update desktop database
  ansible.builtin.command:
    cmd: update-desktop-database ~/.local/share/applications
  changed_when: false
