---

- name: Download neovim nightly
  ansible.builtin.unarchive:
    # src: https://ghp.ci/https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    src: https://ghp.ci/https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
    dest: ~/.local/opt
    remote_src: true
  notify: Upgrade neovim
  tags:
    - upgrade
    - neovim

- name: Install neovide
  ansible.builtin.unarchive:
    src: https://ghp.ci/https://github.com/neovide/neovide/releases/latest/download/neovide-linux-x86_64.tar.gz
    dest: "~/.local/bin/"
    remote_src: true
  changed_when: false
  tags:
    - upgrade
    - neovide

- name: Install neovide.desktop
  ansible.builtin.copy:
    src: files/neovide.desktop
    dest: ~/.local/share/applications/neovide.desktop
    mode: "0644"
  tags:
    - upgrade
    - neovide

- name: Update desktop database
  ansible.builtin.command:
    cmd: update-desktop-database ~/.local/share/applications
  changed_when: false
  tags:
    - upgrade
    - neovide
