---

- name: Install neovim nightly
  tags:
    - upgrade
    - neovim
  block:

    - name: Install/Upgrade neovim nightly under Fedora
      when: ansible_distribution == "Fedora"
      ansible.builtin.unarchive:
        # src: https://ghp.ci/https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        src: https://ghp.ci/https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
        dest: $XDG_DATA_HOME/nvim-nightly
        remote_src: true
        extra_opts:
          - --strip=1
      changed_when: false

    # ansible -m setup HOST -a 'filter=ansible_architecture'
    - name: Install/Upgrade neovim nightly under macOS x86_64/arm64
      when: ansible_distribution == "MacOSX"
      ansible.builtin.unarchive:
        src: https://ghp.ci/https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-{{ ansible_architecture }}.tar.gz
        dest: $XDG_DATA_HOME/nvim-nightly
        remote_src: true
        extra_opts:
          - --strip=1
      changed_when: false


    - name: Symlink nvim/vim bin to /usr/local/bin/
      ansible.builtin.shell: |
        set -o pipefail
        ln -sf $XDG_DATA_HOME/nvim-nightly/bin/nvim /usr/local/bin/nvim
        ln -sf /usr/local/bin/nvim /usr/local/bin/vim
      changed_when: false


- name: Install neovide
  tags:
    - upgrade
    - neovide
  when: ansible_distribution == "Fedora"
  block:

    - name: Install/Upgrade neovide
      ansible.builtin.unarchive:
        src: https://ghp.ci/https://github.com/neovide/neovide/releases/latest/download/neovide-linux-x86_64.tar.gz
        dest: "~/.local/bin/"
        remote_src: true
      changed_when: false

    - name: Download neovide desktop files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        force: true
      loop:
        - { url: '{{ neovide_url_prefix }}/neovide.svg', dest: '~/.local/share/icons/neovide.svg' }
        - { url: '{{ neovide_url_prefix }}/neovide.desktop', dest: '~/.local/share/applications/neovide.desktop' }
      vars:
        # noqa var-naming[no-role-prefix]
        neovide_url_prefix: https://ghp.ci/https://github.com/neovide/neovide/raw/refs/heads/main/assets
      changed_when: false

    - name: Update desktop database
      ansible.builtin.command:
        cmd: update-desktop-database ~/.local/share/applications
      changed_when: false
