---

# /usr/bin/java -Djava.awt.headless=true -Dapple.awt.UIElement=true -jar ~/.local/bin/plantuml.jar /path/to/some.puml
- name: Install plantuml.jar
  ansible.builtin.get_url:
    url: "{{ archives_server }}/plantuml.jar"
    dest: "~/.local/bin"
    mode: "0644"
    force: true
  changed_when: false
  tags:
    - upgrade
    - plantuml
