---

- name: Install tldr python client
  tags:
    - upgrade
    - tldr
  block:

    - name: Install tldr
      ansible.builtin.shell: |
        set -o pipefail
        pip3 install --user tldr
        ~/.local/bin/tldr --print-completion zsh > ~/.local/share/zsh/site-functions/_tldr
      changed_when: false

    - name: Download tldr.zip
      ansible.builtin.unarchive:
        # src: https://tldr-pages.github.io/assets/tldr.zip
        src: https://tldr.sh/assets/tldr.zip
        dest: ~/.cache/tldr/
        remote_src: true
      changed_when: false
      environment: "{{ proxy_env }}"
