---

- name: Install emscripten latest
  ansible.builtin.shell: |
    cd ~/sdk
    git clone https://github.com/emscripten-core/emsdk.git
    cd emsdk
    git pull
    ./emsdk install latest
    ./emsdk activate latest
    source ./emsdk_env.sh
    emcc -v
  changed_when: false
  tags:
    - wasm
