---

- name: Install emscripten latest
  ansible.builtin.shell: |
    cd ~/.local/share/
    git clone https://github.com/emscripten-core/emsdk.git
    cd emsdk
    git pull
    ./emsdk install latest
    ./emsdk activate latest
    source ./emsdk_env.sh
    emcc -v
  changed_when: false
  tags:
    - wasm

# Optimizer and compiler/toolchain library for WebAssembly
- name: Install binaryen
  become: true
  ansible.builtin.dnf:
    name:
      - binaryen

- name: Install wasm-pack
  ansible.builtin.command:
    cmd: cargo install wasm-pack
  changed_when: false
