---

# ----------------------------------------------------------------
# done
# ----------------------------------------------------------------
- name: Check if all done
  ansible.builtin.stat:
    path: "~/doneplay"
  register: done_check

- name: Welcome when all done
  when: done_check.stat.exists
  ansible.builtin.debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: All done end play
  ansible.builtin.meta: end_play
  when: done_check.stat.exists


# ----------------------------------------------------------------
# sudo without password
# ----------------------------------------------------------------
- name: Check if user has sudo access
  ansible.builtin.shell:
    if sudo -n true 2>/dev/null; then
        echo "yes"
    else
        echo "no"
    fi
  changed_when: false
  ignore_errors: true
  register: sudoers_check

- name: Same thing without a password (if skipping is user has sudo access)
  when: sudoers_check.stdout == "no"
  ansible.builtin.shell: |
    set -o pipefail
    echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/$USER"
  changed_when: false

# sudo: xxx: command not found
# Defaults secure_path = /home/ueaner/.local/bin:/home/ueaner/.cargo/bin:/usr/local/sbin:...
# sudo ln -sf /home/ueaner/.cargo/bin/* /usr/local/bin/

# ----------------------------------------------------------------
# prepare tools
# ----------------------------------------------------------------
- name: Install prepare tools
  when: ansible_pkg_mgr == "dnf"
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    name:
      - git
      - zsh
      - util-linux-user
      - wget

# ----------------------------------------------------------------
# rpmfusion
# ----------------------------------------------------------------
- ansible.builtin.include_tasks: rpmfusion.yml

# ----------------------------------------------------------------
# os-release
# ----------------------------------------------------------------
- ansible.builtin.include_tasks: os-release.yml
