---

# ----------------------------------------------------------------
# done
# ----------------------------------------------------------------
- name: Check if all done
  ansible.builtin.stat:
    path: "~/doneplay"
  register: prepare_done_check

- name: Welcome when all done
  when: prepare_done_check.stat.exists
  ansible.builtin.debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: All done end play
  ansible.builtin.meta: end_play
  when: prepare_done_check.stat.exists


# ----------------------------------------------------------------
# sudo without password
# ----------------------------------------------------------------
- name: Check if user has sudo access
  # ansible.builtin.shell: if sudo -n true 2>/dev/null; then echo "yes" else echo "no" fi
  ansible.builtin.shell: sudo -n true 2>/dev/null
  changed_when: false
  ignore_errors: true
  register: prepare_sudoers_check

- name: Same thing without a password (Skip this task if the user has sudo access)
  # when: prepare_sudoers_check.stdout == "no"
  when: prepare_sudoers_check.rc != 0
  ansible.builtin.shell: |
    set -o pipefail
    echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/$USER"
  changed_when: false

# ----------------------------------------------------------------
# prepare permissions for /usr/local/bin
# ----------------------------------------------------------------

# sudo: xxx: command not found
# ln -sf $CARGO_HOME/bin/* /usr/local/bin/
- name: Change the owner of the /usr/local/bin directory to {{ ansible_env.USER }}
  become: true
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'

# ----------------------------------------------------------------
# dnf mirrors and rpmfusion repositories
# ----------------------------------------------------------------
- name: Using Tsinghua/USTC repositories
  when: ansible_distribution == "Fedora"
  ansible.builtin.script: ~/bin/dnf-repos ustc

# ----------------------------------------------------------------
# os-release
# ----------------------------------------------------------------
- name: Setting prepare facts (by include_tasks)
  ansible.builtin.include_tasks: os-release.yml
