#----------------------------------------------------------------
# done
#----------------------------------------------------------------
- name: Check if all done
  stat:
    path: "~/doneplay"
  register: done_check

- name: Welcome when all done
  when: done_check.stat.exists
  debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: All done end play
  meta: end_play
  when: done_check.stat.exists


#----------------------------------------------------------------
# sudo without password
#----------------------------------------------------------------
- name: Same thing without a password
  shell: echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/$USER"

#----------------------------------------------------------------
# prepare tools
#----------------------------------------------------------------
- name: Install prepare tools (if skipping is already installed)
  when: ansible_pkg_mgr == "dnf"
  become: true
  become_method: sudo
  dnf:
    name:
    - git
    - zsh
    - util-linux-user
    - wget

#----------------------------------------------------------------
# rpmfusion
#----------------------------------------------------------------
- name: Install the rpmfusion repo packages (include rpmfusion)
  include_tasks: rpmfusion.yml
