---

# ----------------------------------------------------------------
# done
# ----------------------------------------------------------------
- name: Check if all done
  ansible.builtin.stat:
    path: "~/doneplay"
  register: prepare_done_check

- name: Welcome when all done
  when: prepare_done_check.stat.exists
  ansible.builtin.debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: All done end play
  ansible.builtin.meta: end_play
  when: prepare_done_check.stat.exists


# ----------------------------------------------------------------
# sudo without password
# ----------------------------------------------------------------
- name: Check if user has sudo access
  # ansible.builtin.shell: if sudo -n true 2>/dev/null; then echo "yes" else echo "no" fi
  ansible.builtin.shell: sudo -n true 2>/dev/null
  changed_when: false
  ignore_errors: true
  register: prepare_sudoers_check

- name: Same thing without a password (if skipping is user has sudo access)
  # when: prepare_sudoers_check.stdout == "no"
  when: prepare_sudoers_check.rc != 0
  ansible.builtin.shell: |
    set -o pipefail
    echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/$USER"
  changed_when: false

# sudo: xxx: command not found
# Defaults secure_path = /home/ueaner/.local/bin:/home/ueaner/.cargo/bin:/usr/local/sbin:...
# sudo ln -sf /home/ueaner/.cargo/bin/* /usr/local/bin/

# ----------------------------------------------------------------
# prepare tools
# ----------------------------------------------------------------
- name: Install prepare tools
  when: ansible_pkg_mgr == "dnf"
  become: true
  ansible.builtin.dnf:
    name:
      - git
      - zsh
      - util-linux-user
      - wget

# ----------------------------------------------------------------
# rpmfusion and tsinghua repositories
# ----------------------------------------------------------------
- name: Repositories (by include_tasks)
  ansible.builtin.include_tasks: repos.yml

# ----------------------------------------------------------------
# os-release
# ----------------------------------------------------------------
- name: Setting prepare facts (by include_tasks)
  ansible.builtin.include_tasks: os-release.yml
