---

- name: Using Tsinghua/USTC Repository
  ansible.builtin.script: files/repos.sh
  when: ansible_distribution == "Fedora"

- name: Install RPM Fusion Repository
  block:

    - name: Check if rpmfusion is installed
      ansible.builtin.stat:
        path: "/etc/yum.repos.d/{{ item }}"
      with_items:
        - rpmfusion-free.repo
        - rpmfusion-nonfree.repo
      register: prepare_rpmfusion_check

    # - name: Install the rpmfusion repo packages
    #   when:
    #   - ansible_distribution == "Fedora"
    #   - not prepare_rpmfusion_check.results[0].stat.exists or not prepare_rpmfusion_check.results[1].stat.exists
    #   become: true
    #   ansible.builtin.dnf:
    #     name: "{{ item }}"
    #     state: present
    #   with_items:
    #     - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    #     - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

    # sudo dnf --setopt=localpkg_gpgcheck=1 install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
    # sudo dnf --setopt=localpkg_gpgcheck=1 install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
    - name: Install the rpmfusion repository packages
      when:
        - ansible_distribution == "Fedora"
        - not prepare_rpmfusion_check.results[0].stat.exists or not prepare_rpmfusion_check.results[1].stat.exists
      ansible.builtin.shell: |
        sudo dnf install distribution-gpg-keys -y
        sudo rpmkeys --import /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-$(rpm -E %fedora)
        sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
        sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
      changed_when: false
