# 配置优先级：
# YARN_* 开头的环境变量 > [project]/.yarnrc.yml > $HOME/.yarnrc.yml

npmRegistryServer: https://registry.npmmirror.com

enableGlobalCache: true
# 由于当前配置文件的位置是 $HOME/.yarnrc.yml，所以这里的相对路径是 $HOME 目录
globalFolder: .cache/yarn
# cacheFolder 默认为 globalFolder 下的 cache 目录
# yarn v1 版本的缓存目录在 $HOME/Library/Caches/Yarn/v6
# 注意 v1 v2 版本不要混用，两个版本生成的缓存，不可共用，直接使用 v2+ 版本
# 尽量少使用 npm 命令安装项目包和全局包，npm 缓存和 yarn 缓存不可共用
cacheFolder: .cache/yarn/cache
yarnPath: .cache/yarn/yarn-latest.cjs

# 有部分项目不支持 PnP 协议，如 React Native
# 继续使用原始的 node_modules 目录做依赖管理
nodeLinker: node-modules
