---

- name: Install man-pages.zh
  install-package:
    name: man-pages.zh
    install: |-
      if [[ -x ~/bin/git-sparse-checkout ]]; then
          ~/bin/git-sparse-checkout -r https://github.com/man-pages-zh/manpages-zh -l /tmp/zhman /src/man{1,2,3,4,5,6,7,8,n}
          mv /tmp/zhman/src ~/.local/share/man/zh_CN
      fi
  tags:
    - man

- name: Install tldr
  tags:
    - upgrade
    - tldr
  block:

    - name: Install tldr python client
      ansible.builtin.shell: |
        set -o pipefail
        if which uv >/dev/null 2>&1; then
            uv tool install tldr
        else
            python3 -m ensurepip --upgrade --user
            python3 -m pip install --upgrade --user tldr
        fi

        ~/.local/bin/tldr --print-completion zsh > ~/.local/share/zsh/site-functions/_tldr
        tldr --version
      changed_when: false

    # - name: Install tldr-pages
    #   install-package:
    #     name: "{{ item.src }}"
    #     placeholders:
    #       repo: tldr-pages/tldr
    #     template: "{{ template.github.latest }}"
    #     archives:
    #       - "{{ item.src }}.zip"
    #     dst: ~/.cache/tldr/{{ item.dst }}
    #   loop:
    #     - { src: "tldr-pages.en", dst: "pages" }
    #     - { src: "tldr-pages.zh", dst: "pages.zh" }

    - name: Create tldr pages directory
      ansible.builtin.file:
        path: "~/.cache/tldr/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - pages
        - pages.zh

    - name: Install tldr-pages
      ansible.builtin.unarchive:
        src: "{{ GITHUB_PROXY }}https://github.com/tldr-pages/tldr/releases/latest/download/{{ item.src }}.zip"
        dest: ~/.cache/tldr/{{ item.dst }}
      changed_when: false
      loop:
        - { src: "tldr-pages.en", dst: "pages" }
        - { src: "tldr-pages.zh", dst: "pages.zh" }
