---

- name: Ensure Tmux is installed
  tags:
    - upgrade
    - tmux
  block:
    - name: Install Tmux (Fedora)
      when: ansible_distribution == "Fedora"
      become: true
      ansible.builtin.dnf:
        name: tmux
        state: present

    - name: Install Tmux (macOS)
      when: ansible_system == "Darwin"
      environment: "{{ brew_environment }}"
      ansible.builtin.shell: |-
        if ! brew list --formula tmux >/dev/null 2>&1; then
            brew install tmux
        fi
      changed_when: false

    - name: Install terminfo for tmux (macOS)
      when: ansible_system == "Darwin"
      environment: "{{ brew_environment }}"
      ansible.builtin.shell: |-
        if ! brew list --formula ncurses >/dev/null 2>&1; then
            HOMEBREW_PREFIX=$(brew --prefix)
            ${HOMEBREW_PREFIX}/opt/ncurses/bin/infocmp tmux-256color > /tmp/tmux-256color.info
            ${HOMEBREW_PREFIX}/opt/ncurses/bin/infocmp tmux-direct > /tmp/tmux-direct.info
            /usr/bin/tic -xe tmux-256color /tmp/tmux-256color.info
            /usr/bin/tic -xe tmux-direct /tmp/tmux-direct.info
        else
            cd /tmp
            curl -LO https://invisible-island.net/datafiles/current/terminfo.src.gz && gunzip terminfo.src.gz
            tic -xe tmux-direct,tmux-256color terminfo.src
        fi
      changed_when: false


- name: Install gitmux
  install-package:
    name: gitmux
    placeholders:
      repo: arl/gitmux
      version: "{{ template.github.version }}"
    template: "{{ template.github.archive }}"
    archives:
      # https://github.com/arl/gitmux/releases/download/v0.11.5/gitmux_v0.11.5_linux_amd64.tar.gz
      - gitmux_<version>_linux_amd64.tar.gz
      - gitmux_<version>_linux_arm64.tar.gz
      - gitmux_<version>_macOS_amd64.tar.gz
      - gitmux_<version>_macOS_arm64.tar.gz
    include:
      - gitmux
    dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
    postinstall: |-
      gitmux -V
