# Copy this to ~/.config/xremap/config.yml

---

keymap:
  - name: macOS-ish basic
    exact_match: true
    application:
      # tmux shortcuts are defined with Alacritty
      not: [Alacritty]
    remap:
      # Super-tab switch applications
      #  Ctrl-tab switch tabs
      #  Super-`  switch windows of application
      # Window / Tab
      Super-n: C-n              # new window
      Super-t: C-t              # new tab
      Super-w: C-w              # close tab
      Super-Shift-t: C-Shift-t  # reopen the last closed tab
      Super-Shift-KEY_RIGHTBRACE: C-KEY_TAB       # ] next tab
      Super-Shift-KEY_LEFTBRACE:  C-Shift-KEY_TAB # [ prev tab
      Super-KEY_COMMA: C-KEY_COMMA  # Super-, preferences / settings
      Super-i: M-Enter          # Super-i -> Alt-Enter: Properties
      # Super-h                 # set in gsettings
      # Super-q                 # set in gsettings

      # Editting
      Super-z: C-z              # undo
      Super-Shift-z: C-Shift-z  # redo
      Super-x: C-x              # Cut
      Super-c: C-c              # Copy
      Super-v: C-v              # Paste
      Super-f: C-f              # find
      Super-g: C-g              # find next
      Super-Shift-g: C-Shift-g  # find previous
      Super-l: [Esc, C-l]       # address bar / select line
      Super-a: C-KEY_SLASH      # select all, use `C-/` instead of `C-a`
      Super-o: C-o              # open options / open choose file dialog
      Super-p: C-p              # print
      Super-s: C-s              # save
      # Ctrl-u: [Shift-Home, Backspace]       # Emacs C-u

  - name: macOS-ish font zoom
    exact_match: true
    remap:
      Super-KEY_0: C-KEY_0          # reset font size
      Super-KEY_EQUAL: C-KEY_EQUAL  # increase font size
      Super-KEY_MINUS: C-KEY_MINUS  # decrease font size

  - name: Chrome
    exact_match: true
    application:
      only: [Google-chrome, google-chrome]
    remap:
      Super-Shift-n: C-Shift-n  # open a new window in Incognito mode
      Super-Alt_l-i: C-Shift-i  # open developer tools
      Super-j: C-j              # open download page
      Super-d: C-d              # save page to bookmarks
      Super-r: C-r              # reload page
      Super-9: C-9              # jump to the last page
