#!/usr/bin/env bash
#
# Ansible Core 2.19 supports Python versions:
# - Control Node: Python 3.11+
# - Managed (Target) Nodes: Python 3.8+
#
# See:
# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
# https://access.redhat.com/articles/7128367
#

set -e

export ANSIBLE_CONFIG=~/.ansible/ansible.cfg
export PYTHONUSERBASE=~/.local

# ----------------------------------------------------------------
# Ensure ~/.dotfiles exists
# ----------------------------------------------------------------

if [[ ! -d "$HOME/.dotfiles" ]]; then
    echo "# git clone dotfiles"
    # git config --global http.version HTTP/1.1
    git clone --bare https://github.com/ueaner/dotfiles.git "$HOME/.dotfiles"
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" checkout
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" config --local status.showUntrackedFiles no
fi

# ----------------------------------------------------------------
# install ansible
# ----------------------------------------------------------------

ANSIBLE_BIN_PATH=~/.local/bin

if [[ ! -x "$ANSIBLE_BIN_PATH/ansible" ]]; then
    export UV_PYTHON_INSTALL_MIRROR=${GITHUB_PROXY}https://github.com/astral-sh/python-build-standalone/releases/download
    export UV_INDEX_URL=https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

    # curl -LsSf ${GITHUB_PROXY}https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh -s -- --help
    if [[ ! -x $XDG_BIN_HOME/uv ]]; then
        export UV_INSTALLER_GITHUB_BASE_URL=${GITHUB_PROXY}https://github.com
        export UV_NO_MODIFY_PATH=1
        export INSTALLER_PRINT_VERBOSE=1

        # curl https://astral.sh/uv/install.sh -sSf | sh
        curl -LsSf ${GITHUB_PROXY}https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh
    else
        uv self update
    fi

    uv python list --managed-python --only-installed
    uv python list --no-managed-python

    if [[ -d ~/.ansible ]]; then
        cd ~/.ansible
        # ~/.ansible/.venv/bin/ansible --version
        uv run ansible --version

        ANSIBLE_BIN_PATH=~/.ansible/.venv/bin
    else
        uv tool install --upgrade ansible
    fi
fi

$ANSIBLE_BIN_PATH/ansible --version
$ANSIBLE_BIN_PATH/ansible-config dump --only-changed -t all

# ----------------------------------------------------------------
# Let's gooooo
# ----------------------------------------------------------------
$ANSIBLE_BIN_PATH/ansible-playbook ~/.ansible/unix.yml --ask-become-pass
