#!/usr/bin/env bash
#
# Ansible Core 2.19 supports Python versions:
# - Control Node: Python 3.11+
# - Managed (Target) Nodes: Python 3.8+
#
# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
# https://access.redhat.com/articles/7128367
#

set -e

export ANSIBLE_CONFIG=~/.ansible/ansible.cfg
export PYTHONUSERBASE=~/.local

# ----------------------------------------------------------------
# Ensure ~/.dotfiles exists
# ----------------------------------------------------------------

if [[ ! -d "$HOME/.dotfiles" ]]; then
    echo "# git clone dotfiles"
    # git config --global http.version HTTP/1.1
    git clone --bare https://github.com/ueaner/dotfiles.git "$HOME/.dotfiles"
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" checkout
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" config --local status.showUntrackedFiles no
fi

# ----------------------------------------------------------------
# install ansible
# ----------------------------------------------------------------

ANSIBLE_BIN_PATH=~/.local/bin

if [[ ! -x "$ANSIBLE_BIN_PATH/ansible" ]]; then
    if command -v uv >/dev/null; then
        # uv tool install --upgrade ansible
        cd ~/.ansible
        # install ansible
        uv run ansible --version
        # ~/.ansible/.venv/bin/ansible --version
        ANSIBLE_BIN_PATH=~/.ansible/.venv/bin
    else
        if ! python3 -m pip --version &>/dev/null; then
            # install & upgrade pip
            python3 -m ensurepip --upgrade --user
            python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com --upgrade --user pip
        fi

        # install ansible
        python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com --user ansible
    fi
fi

$ANSIBLE_BIN_PATH/ansible --version
$ANSIBLE_BIN_PATH/ansible-config dump --only-changed -t all

# ----------------------------------------------------------------
# Let's gooooo
# ----------------------------------------------------------------
$ANSIBLE_BIN_PATH/ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages task=download" --tags all-packages
$ANSIBLE_BIN_PATH/ansible-playbook ~/.ansible/unix.yml --ask-become-pass
