# vim: set filetype=yaml.ansible:
---

# Usage Examples:
# ansible-playbook ~/.ansible/unix.yml --list-tasks
# ansible-playbook ~/.ansible/unix.yml --list-tags
#
# ansible-playbook ~/.ansible/unix.yml -e "role=desktop"
# ansible-playbook ~/.ansible/unix.yml -e "role=terminal"
# ansible-playbook ~/.ansible/unix.yml -e "role=fonts"
# ansible-playbook ~/.ansible/unix.yml -e "role=lang" --tags go
# ansible-playbook ~/.ansible/unix.yml -e "role=services" --tags frpc -vvv
# ansible-playbook ~/.ansible/unix.yml -e "role=apps"

- name: Setup Unix Workstation
  hosts: local
  vars:
    # By default, "role=all" is overridden by the `--extra-vars "role=xxx"` passed on the command line.
    role: all
  environment:
    # Defaults env for target nodes
    XDG_CONFIG_HOME: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME ~ '/.config') }}"
    XDG_CACHE_HOME: "{{ ansible_env.XDG_CACHE_HOME | default(ansible_env.HOME ~ '/.cache') }}"
    XDG_DATA_HOME: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME ~ '/.local/share') }}"
    XDG_STATE_HOME: "{{ ansible_env.XDG_STATE_HOME | default(ansible_env.HOME ~ '/.local/state') }}"
    XDG_BIN_HOME: "{{ ansible_env.XDG_BIN_HOME | default(ansible_env.HOME ~ '/.local/bin') }}"
    GITHUB_PROXY: "{{ lookup('env', 'GITHUB_PROXY', default='') }}"
    # The PATH variable is defined in group_vars/all
    PATH: "{{ PATH }}"
  roles:
    - role: prelude

    - role: desktop  # macOS-ish Desktop Environment
      when: (role == "all") or (role == "desktop")
    - role: terminal  # Terminal Environment
      when: (role == "all") or (role == "terminal")
    - role: fonts
      when: (role == "all") or (role == "fonts")
    # ansible-playbook ~/.ansible/unix.yml --extra-vars "role=lang" --tags "go" -vvv
    - role: lang  # Programming languages
      when: (role == "all") or (role == "lang")
    - role: services
      when: (role == "all") or (role == "services")
    - role: apps
      when: (role == "all") or (role == "apps")
    - role: done
      when: (role == "all") or (role == "done")
