---

- name: Start and enable shadowsocks-rust-local service
  # noqa command-instead-of-module
  ansible.builtin.command: systemctl --user enable --now shadowsocks-rust-local
  changed_when: false
  when: ansible_distribution == "Fedora"

# Use ~/.config/autostart/xremap.desktop on desktop environment startup
- name: Start xremap service
  # noqa command-instead-of-module
  ansible.builtin.command: systemctl --user start xremap
  changed_when: false
  when: ansible_distribution == "Fedora"
