---

# Use ~/.config/autostart/xremap.desktop on desktop environment startup
- name: Start xremap service
  # noqa command-instead-of-module
  ansible.builtin.command: systemctl --user start xremap
  changed_when: false

- name: Need to reboot after installing wireless driver under MacBook
  # noqa command-instead-of-module
  ansible.builtin.debug:
    msg: Need to reboot after installing wireless driver under MacBook
