- name: Installed Golang
  command:
    cmd: "~/go/bin/go version"
  register: go_version
- debug: var=go_version.stdout

- name: Installed Rust
  command:
    cmd: "~/.cargo/bin/rustc --version"
  register: rust_version
- debug: var=rust_version.stdout

- name: Installed Node.js
  command:
    cmd: "~/.local/share/fnm/aliases/default/bin/node --version"
  register: node_version
- debug: var=node_version.stdout

- name: Installed Deno
  command:
    cmd: "~/.cargo/bin/deno --version"
  register: deno_version
- debug: var=deno_version.stdout_lines
