---

# ----------------------------------------------------------------
# dotfiles
# ----------------------------------------------------------------
- name: Check if dotfiles exists
  ansible.builtin.stat:
    path: "$HOME/.dotfiles"
  register: dotshell_dotfiles_check

- name: Install dotfiles (Skip this task if already installed)
  # noqa command-instead-of-module
  ansible.builtin.shell: |
    git config --global http.version HTTP/1.1
    git clone --bare https://github.com/ueaner/dotfiles.git $HOME/.dotfiles
    git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
    git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
  changed_when: false
  when: not dotshell_dotfiles_check.stat.exists

# ----------------------------------------------------------------
# dotlocal
# ----------------------------------------------------------------
- name: Check if dotlocal exists
  ansible.builtin.stat:
    path: "$HOME/.dotlocal"
  register: dotshell_dotlocal_check

- name: Install dotlocal (Skip this task if already installed)
  # noqa command-instead-of-module
  ansible.builtin.shell: |
    git config --global http.version HTTP/1.1
    git clone --bare https://github.com/ueaner/local.git $HOME/.dotlocal
    git --git-dir=$HOME/.dotlocal/ --work-tree=$HOME/.local checkout
    git --git-dir=$HOME/.dotlocal/ --work-tree=$HOME/.local config --local status.showUntrackedFiles no
  changed_when: false
  when: not dotshell_dotlocal_check.stat.exists

# ----------------------------------------------------------------
# nvimrc
# ----------------------------------------------------------------
- name: Check if nvimrc exists
  ansible.builtin.stat:
    path: "$HOME/.config/nvim"
  register: dotshell_nvimrc_check

- name: Install nvimrc (Skip this task if already installed)
  # noqa command-instead-of-module
  ansible.builtin.shell: |
    git clone https://github.com/ueaner/nvimrc.git $HOME/.config/nvim
  changed_when: false
  when: not dotshell_nvimrc_check.stat.exists

# ----------------------------------------------------------------
# zsh
# ----------------------------------------------------------------
- name: Use zsh as the default login shell
  ansible.builtin.shell: chsh -s $(which zsh)
  changed_when: false
  when: "'/zsh' not in ansible_env.SHELL"
