---

- name: Install Noto CJK Fonts
  when:
    - ansible_distribution == "Fedora"
    - chinese
  become: true
  ansible.builtin.dnf:
    name:
      # pre-installed: google-noto-*-cjk-vf-fonts
      # https://fedoraproject.org/wiki/Changes/Noto_CJK_Variable_Fonts
      - google-noto-sans-cjk-vf-fonts
      - google-noto-sans-mono-cjk-vf-fonts
      - google-noto-serif-cjk-vf-fonts
      # Fixed com.baidu.NetDisk font display issue
      - google-noto-sans-cjk-fonts
      - google-noto-serif-cjk-fonts
