# DE: macOS-ish desktop environment (Shortcuts & Gestures), Input Method
---

- name: Configure GNOME as a macOS-ish desktop environment
  when: desktop == "GNOME"
  block:

    # Install the extension, then re-login and enable the extension using `gnome-extensions enable <uuid>`.
    # - name: Install GNOME Shell extensions
    #   when: desktop == "GNOME"
    #   install-package:
    #     name: "{{ item }}"
    #     placeholders:
    #       version: curl -s --get -L https://extensions.gnome.org/extension-info/ --data-urlencode shell_version={{ gnome_shell_version }} --data-urlencode uuid={{ item }} | jq -r .version_tag
    #     template: https://extensions.gnome.org/download-extension/{{ item }}.shell-extension.zip?version_tag=<version>
    #     archives: "{{ item }}.shell-extension.zip"
    #     dst: ~/.local/share/gnome-shell/extensions/{{ item }} # defaults to $XDG_BIN_HOME
    #     postinstall: gnome-extensions enable {{ item }} >/dev/null 2>&1

    # 1. First use Firefox to visit https://extensions.gnome.org/local/ and install the GNOME Shell Integration Extension
    # 2. After re-login, use Firefox to revisit https://extensions.gnome.org/local/ and enable the installed GNOME Shell Extensions
    - name: Install GNOME shell extensions
      # delegate_to: localhost
      ansible.builtin.shell: |-
        set -o pipefail
        mkdir -p ~/.cache/archives
        cd ~/.cache/archives
        uuid={{ item }}

        gnome-shell-extensions-downloader $uuid

        echo 'Install the extension, then re-login and enable the extension using `gnome-extensions enable <uuid>`.'
        # unzip -q $uuid.shell-extension.zip -d $HOME/.local/share/gnome-shell/extensions/$uuid
        gnome-extensions install --force $uuid.shell-extension.zip
        gnome-extensions enable $uuid >/dev/null 2>&1
      changed_when: false
      loop:
        - gestureImprovements@gestures # NOTE: Depends on gnome-shell-extensions-downloader
        - gnome-shell-go-to-last-workspace@github.com # Quickly toggle between two workspaces with one key
        - xremap@k0kubun.com # Allow xremap to fetch the focused app name using D-Bus
        - clipboard-indicator@tudmotu.com # <Super>bracketleft/bracketright
        - kimpanel@kde.org # Input Method Panel
        - desktop-lyric@tuberry # com.github.gmg137.netease-cloud-music-gtk
        - system-monitor@gnome-shell-extensions.gcampax.github.com # Monitor system from the top bar
        - native-window-placement@gnome-shell-extensions.gcampax.github.com # Arrange windows in overview in a more compact way.
        - color-picker@tuberry
        - gsconnect@andyholmes.github.io

    - name: Setup a macOS-ish desktop environment (Shortcuts, Gestures)
      ansible.builtin.command: ~/bin/gnome-gsettings-macos-ish
      changed_when: false

    - name: Configure libpinyin
      when: chinese
      ansible.builtin.command: ~/bin/gnome-gsettings-libpinyin
      changed_when: false

- name: Configure GNOME Desktop Environment
  when: desktop == "GNOME"
  block:

    - name: Make gnome more lightweight
      ansible.builtin.command: ~/bin/gnome-lightweight
      changed_when: false

    - name: Configure GNOME UI appearance
      ansible.builtin.command: ~/bin/gnome-gsettings-ui
      changed_when: false

    - name: Configure GNOME Apps
      ansible.builtin.command: ~/bin/gnome-gsettings-apps
      changed_when: false

- name: Configure Sway Desktop Environment
  when: desktop == "Sway"
  block:
    - name: See Sway config
      ansible.builtin.debug:
        msg: "See ~/.config/sway/config"

    - name: Set Sway backgrounds
      ansible.builtin.command: ~/bin/sway-bg
      changed_when: false

    - name: Install wtype
      become: true
      ansible.builtin.command: sudo dnf install -y wtype
      changed_when: false

- name: Configure macOS Desktop Environment
  when: ansible_system == "Darwin"
  block:
    - name: Configure macOS basic
      ansible.builtin.command: ~/bin/macos-basic
      changed_when: false

    - name: Install Hammerspoon (macOS)
      when: ansible_system == "Darwin"
      environment: "{{ brew_environment }}"
      ansible.builtin.shell: |-
        if ! brew list --cask hammerspoon >/dev/null 2>&1; then
            brew install --cask hammerspoon
        fi
      changed_when: false
