# macOS-ish keyboard remap with xremap
---

# Install and start xremap service
# https://github.com/ueaner/dotfiles/blob/main/.config/systemd/user/xremap.service
# https://github.com/ueaner/dotfiles/tree/main/.config/autostart/xremap.desktop

- name: Install xremap (GNOME Wayland)
  when:
    - ansible_system == "Linux"
    - desktop == "GNOME"
  ansible.builtin.unarchive:
    src: "{{ GITHUB_PROXY }}https://github.com/xremap/xremap/releases/latest/download/xremap-linux-x86_64-gnome.zip"
    dest: "~/.local/bin"
    remote_src: true
  notify: Start xremap service

- name: Install xremap (Sway)
  when:
    - ansible_system == "Linux"
    - desktop == "Sway"
  ansible.builtin.unarchive:
    src: "{{ GITHUB_PROXY }}https://github.com/xremap/xremap/releases/latest/download/xremap-linux-x86_64-wlroots.zip"
    dest: "~/.local/bin"
    remote_src: true
  notify: Start xremap service

# Required: Linux
# - name: Install xremap (Linux)
#   when: ansible_system == "Linux"
#   tags:
#     - xremap
#   block:
#
#     - name: Install xremap (GNOME)
#       when: desktop == "GNOME"
#       install-package:
#         name: xremap
#         placeholders:
#           repo: xremap/xremap
#         template: "{{ template.github.latest }}"
#         archives:
#           - xremap-linux-x86_64-gnome.zip
#         dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
#         include:
#           - xremap
#         postinstall: |-
#           xremap --version
#
#     - name: Install xremap (Sway)
#       when: desktop == "Sway"
#       install-package:
#         name: xremap
#         placeholders:
#           repo: xremap/xremap
#         template: "{{ template.github.latest }}"
#         archives:
#           - xremap-linux-x86_64-wlroots.zip
#         dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
#         include:
#           - xremap
#         postinstall: |-
#           xremap --version
