---

# https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
# - name: Install/Upgrade VSCode via dnf (Fedora)
#   when: ansible_distribution == "Fedora"
#   ansible.builtin.shell: |-
#     set -o pipefail
#     sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
#     sudo tee /etc/yum.repos.d/vscode.repo >/dev/null <<'REPO'
#     [code]
#     name=Visual Studio Code
#     baseurl=https://packages.microsoft.com/yumrepos/vscode
#     enabled=1
#     autorefresh=1
#     type=rpm-md
#     gpgcheck=1
#     gpgkey=https://packages.microsoft.com/keys/microsoft.asc
#     REPO
#
#     sudo dnf check-update
#     # sudo dnf install code # or code-insiders
#   changed_when: false

- name: Install apps via dnf (Fedora)
  when: ansible_distribution == "Fedora"
  become: true
  ansible.builtin.dnf:
    name:
      - wl-clipboard
      - xlsclients # list x11 client applications running on a display
      # - code # or code-insiders
      - android-tools

# - name: Install/Upgrade web apps
#   when: ansible_distribution == "Fedora"
#   ansible.builtin.include_tasks: web.yml

- name: Install/Upgrade apps via flatpak (Fedora)
  when: ansible_distribution == "Fedora"
  ansible.builtin.shell: |-
    set -o pipefail
    if [[ -n "{{ item.desktop }}" && "{{ desktop }}" != "{{ item.desktop }}" ]]; then
        exit 0
    fi
    flatpak install --user {{ item.name }}
  loop:
    # - { name: ca.desrt.dconf-editor, desktop: GNOME }
    # - { name: com.baidu.NetDisk }
    - { name: com.google.Chrome }
    - { name: com.tencent.WeChat }
    - { name: com.github.gmg137.netease-cloud-music-gtk }
    # - { name: io.gitlab.news_flash.NewsFlash }
    # - { name: io.podman_desktop.PodmanDesktop }
    # - { name: com.wps.Office }
    # - { name: com.tencent.wemeet }
    # - { name: dev.zed.Zed }
    # - { name: io.github.mhogomchungu.media-downloader }
    # - { name: com.github.tchx84.Flatseal }
    # Add the following to `~/.local/share/flatpak/overrides/com.qq.QQ` to enable wayland or configure with Flatseal
    # [Context]
    # sockets=wayland;!x11
    # - { name: com.qq.QQ }
    # - { name: org.blender.Blender }
    # - { name: org.videolan.VLC }
    # - { name: org.shotcut.Shotcut }
    # - { name: com.obsproject.Studio }
    # - { name: org.inkscape.Inkscape }
    # - { name: org.gimp.GIMP }
    # - { name: in.srev.guiscrcpy }
    # - { name: eu.nokun.MirrorHall } # Use Linux devices as second screens
    # - { name: org.freedesktop.Bustle }
    # - { name: org.gnome.Sudoku }
  changed_when: false

# Use lima-vm whenever possible
- name: Install apps via brew (macOS)
  when: ansible_system == "Darwin"
  environment: "{{ brew_environment }}"
  ansible.builtin.shell: |-
    set -o pipefail
    brew install --cask {{ item }}
  loop:
    - baidunetdisk
    - google-chrome
    - wechat
    - dingtalk
    - visual-studio-code
    - android-platform-tools
    - appcleaner
    - maccy
    # - kap
    # - keycastr
    # - tencent-docs
    # - drawio
    # - wpsoffice
    # - the-unarchiver
    # - tencent-meeting
    # - vlc
    # - omnigraffle
    # - pdfexpert
    # - wireshark-app
    # - charles
    # - tableplus
    # - qq
  notify:
    - Disable netdisk_service automatic startup
