---

- name: Start and enable shadowsocks-rust-local service
  # noqa command-instead-of-module
  ansible.builtin.command: systemctl --user enable --now shadowsocks-rust-local
  changed_when: false
  when: ansible_distribution == "Fedora"
