# ----------------------------------------------------------------
# Deno, Install/Upgrade
# ----------------------------------------------------------------

---

- name: Install/Upgrade Deno
  tags:
    - upgrade
    - deno
  block:

    # Install deno, check file stat

    - name: Check if deno is installed
      ansible.builtin.stat:
        path: "~/.local/bin/deno"
      register: lang_deno_check

    - name: Installing Deno (Skip this task if already installed)
      when: not lang_deno_check.stat.exists
      ansible.builtin.unarchive:
        src: https://github.com/denoland/deno/releases/download/v{{ versions.deno }}/deno-x86_64-unknown-linux-gnu.zip
        dest: "~/.local/bin/"
        remote_src: true
      changed_when: false

    # Upgrade deno, check version

    - name: Check if deno version is {{ versions.deno }}
      ansible.builtin.command:
        cmd: "~/.local/bin/deno --version"
      changed_when: false
      register: lang_deno_version

    - name: Upgrading Deno (Skip this task if version is already {{ versions.deno }})
      when: "versions.deno not in lang_deno_version.stdout"
      ansible.builtin.unarchive:
        src: https://github.com/denoland/deno/releases/download/v{{ versions.deno }}/deno-x86_64-unknown-linux-gnu.zip
        dest: "~/.local/bin/"
        remote_src: true
      changed_when: false

    # Deno Installation Finished, echo version
    - name: Deno Installation Finished
      ansible.builtin.shell: |
        ~/.local/bin/deno --version
        ~/.local/bin/deno completions zsh > ~/.local/share/zsh/site-functions/_deno
      changed_when: false
      register: lang_deno_version

    - name: DEBUG deno version
      ansible.builtin.debug:
        var: lang_deno_version.stdout_lines
