# ----------------------------------------------------------------
# Golang, Install/Upgrade
# ----------------------------------------------------------------

---

# sudo dnf install go --setopt=install_weak_deps=False
- name: Install/Upgrade Golang
  tags:
    - upgrade
    - go
  block:

    # Install golang, check file stat

    - name: Check if go is installed
      ansible.builtin.stat:
        path: "$XDG_DATA_HOME/go/bin/go"
      register: lang_go_check

    - name: Install Golang
      when: not lang_go_check.stat.exists
      ansible.builtin.unarchive:
        src: https://dl.google.com/go/go{{ versions.go }}.linux-amd64.tar.gz
        dest: "$XDG_DATA_HOME/"
        remote_src: true
      changed_when: false

    - name: Symlink golang bin to /usr/local/bin/
      ansible.builtin.command:
        cmd: ln -sf $XDG_DATA_HOME/go/bin/* /usr/local/bin/
      changed_when: false

    # Upgrade golang, check version
    # go install golang.org/dl/go{{ versions.go }}@latest
    # go{{ versions.go }} download

    - name: Check if golang version is {{ versions.go }}
      ansible.builtin.command:
        cmd: "go version"
      changed_when: false
      register: lang_go_version

    - name: Upgrading Golang (Skip this task if version is already {{ versions.go }})
      when: "versions.go not in lang_go_version.stdout"
      ansible.builtin.unarchive:
        src: https://dl.google.com/go/go{{ versions.go }}.linux-amd64.tar.gz
        dest: "$XDG_DATA_HOME/"
        remote_src: true
      changed_when: false

    - name: Symlink golang bin to /usr/local/bin/
      ansible.builtin.command:
        cmd: ln -sf $XDG_DATA_HOME/go/bin/* /usr/local/bin/
      changed_when: false

    - name: Install zsh completion for go
      when: ansible_user_shell.endswith('zsh')
      ansible.builtin.get_url:
        url: https://github.com/zsh-users/zsh-completions/raw/refs/heads/master/src/_golang
        dest: "~/.local/share/zsh/site-functions/"
        mode: "0644"
        force: true

    # Golang Installation Finished, echo version

    - name: Golang Installation Finished
      ansible.builtin.command:
        cmd: "go version"
      changed_when: false
      register: lang_go_version

    - name: DEBUG go version
      ansible.builtin.debug:
        var: lang_go_version.stdout
