# ----------------------------------------------------------------
# Lang, Install/Upgrade
# ----------------------------------------------------------------

---

# ----------------------------------------------------------------
# Golang
# ----------------------------------------------------------------
- name: Install/Upgrade Golang (include_tasks)
  ansible.builtin.include_tasks: go.yml
  tags:
    - upgrade
    - go

# ----------------------------------------------------------------
# Rust
# ----------------------------------------------------------------
- name: Install/Upgrade Rust (include_tasks)
  ansible.builtin.include_tasks: rust.yml
  tags:
    - upgrade
    - rust

# ----------------------------------------------------------------
# Node.js
# ----------------------------------------------------------------
- name: Install/Upgrade Node.js (include_tasks)
  ansible.builtin.include_tasks: node.yml
  tags:
    - upgrade
    - node

# ----------------------------------------------------------------
# Deno
# ----------------------------------------------------------------
- name: Install/Upgrade Deno (include_tasks)
  ansible.builtin.include_tasks: deno.yml
  tags:
    - upgrade
    - deno


#
# Combining `when` to implement `Tags AND operators`
#
# main.yml:
# Not executed by default, only executed when the `upgrade` tag parameter is passed in.
# - name: Upgrade lang
#   when: "'upgrade' in ansible_run_tags"
#   ansible.builtin.include_tasks: upgrade.yml
#   tags:
#     - upgrade

# upgrade.yml:
# Tags AND operators, eg: --tags "upgrade,go"
# - name: Just Upgrade Go
#   when:
#     - '"upgrade" in ansible_run_tags'
#     - '"go" in ansible_run_tags'
#   ansible.builtin.debug:
#     msg: "Just upgrade golang"
#   tags:
#     - upgrade
#     - go
