#----------------------------------------------------------------
# Golang
#----------------------------------------------------------------
- name: Check if go is installed
  stat:
    path: "~/go/bin/go"
  register: go_check

- name: Installing Golang (if skipping is already installed)
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go{{ versions.go }}.linux-amd64.tar.gz
    dest: "~"
    remote_src: true
  when: not go_check.stat.exists
  notify: Installed Golang

#----------------------------------------------------------------
# Rust
#----------------------------------------------------------------
- name: Check if rust is installed
  stat:
    path: "~/.cargo/bin/rustc"
  register: rust_check

- name: Installing Rust (if skipping is already installed)
  # -y: auto accept options
  shell: curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y
  when: not rust_check.stat.exists
  notify: Installed Rust

#----------------------------------------------------------------
# Node.js
#----------------------------------------------------------------
- name: Check if node is installed
  stat:
    path: "~/.local/share/fnm/aliases/default/bin/node"
  register: node_check

- name: Installing Node.js (if skipping is already installed)
  shell: |
    ~/.cargo/bin/cargo install fnm
    ~/.cargo/bin/fnm install {{ versions.node }}
    ~/.cargo/bin/fnm default {{ versions.node }}
    ~/.local/share/fnm/aliases/default/bin/corepack enable pnpm
  when: not node_check.stat.exists
  notify: Installed Node.js

#----------------------------------------------------------------
# Deno
#----------------------------------------------------------------
- name: Check if deno is installed
  stat:
    path: "~/.cargo/bin/deno"
  register: deno_check

- name: Installing Deno (if skipping is already installed)
  ansible.builtin.unarchive:
    src: https://ghproxy.com/https://github.com/denoland/deno/releases/download/v{{ versions.deno }}/deno-x86_64-unknown-linux-gnu.zip
    dest: "~/.cargo/bin/"
    remote_src: true
  when: not deno_check.stat.exists
  notify: Installed Deno
