# ----------------------------------------------------------------
# Node.js, Install/Upgrade
# ----------------------------------------------------------------

---

- name: Install/Upgrade Node.js
  tags:
    - upgrade
    - node
  environment:
    FNM_DIR: "{{ ansible_env.FNM_DIR | default(ansible_env.HOME ~ '/.local/share/fnm') }}"
    CARGO_INSTALL_ROOT: "{{ ansible_env.CARGO_INSTALL_ROOT | default(ansible_env.HOME ~ '/.local/bin') }}"
  block:

    # Install node.js, check file stat

    - name: Check if node.js is installed
      ansible.builtin.stat:
        path: "$FNM_DIR/aliases/default/bin/node"
      register: lang_node_check

    - name: Installing Node.js (Skip this task if already installed)
      when: not lang_node_check.stat.exists
      ansible.builtin.shell: |
        cargo install fnm
        fnm install {{ versions.node }}
        fnm default {{ versions.node }}
        $FNM_DIR/aliases/default/bin/corepack use pnpm@latest
        $FNM_DIR/aliases/default/bin/corepack enable pnpm
        $FNM_DIR/aliases/default/bin/pnpm config set global-bin-dir ~/.local/bin
      changed_when: false
      environment:
        COREPACK_NPM_REGISTRY: "https://registry.npmmirror.com"

    # Upgrade node.js, check version

    - name: Check if node.js version is {{ versions.node }}
      ansible.builtin.command:
        cmd: "$FNM_DIR/aliases/default/bin/node --version"
      changed_when: false
      register: lang_node_version

    - name: Upgrading Node.js (Skip this task if version is already {{ versions.node }})
      when: "versions.node not in lang_node_version.stdout"
      ansible.builtin.shell: |
        cargo install fnm
        fnm install {{ versions.node }}
        fnm default {{ versions.node }}
        $FNM_DIR/aliases/default/bin/corepack use pnpm@latest
        $FNM_DIR/aliases/default/bin/corepack enable pnpm
      changed_when: false
      environment:
        COREPACK_NPM_REGISTRY: "https://registry.npmmirror.com"

    # Node.js Installation Finished, echo version

    - name: Node.js Installation Finished
      ansible.builtin.command:
        cmd: "$FNM_DIR/aliases/default/bin/node --version"
      changed_when: false
      register: lang_node_version

    - name: DEBUG node version
      ansible.builtin.debug:
        var: lang_node_version.stdout
