# curl -sSL https://install.python-poetry.org | python3 -
# will be installed to the below path:
# - ~/.local/share/pypoetry
# - ~/.local/bin/poetry
# - ~/.config/pypoetry/config.toml
# poetry config --list -vvv
# poetry config repositories.aliyun https://mirrors.aliyun.com/pypi/simple/

[repositories.aliyun]
url = "https://mirrors.aliyun.com/pypi/simple/"
