---

- name: Modify flathub remote repository to sjtu
  # ~/.local/share/flatpak/repo/config
  ansible.builtin.shell: |
    flatpak --user remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
    wget https://mirror.sjtu.edu.cn/flathub/flathub.gpg -O /tmp/flathub.gpg
    flatpak --user remote-modify --gpg-import=/tmp/flathub.gpg flathub
  changed_when: false

# chrome://flags/#ozone-platform-hint -> Preferred Ozone platform -> Wayland
# See: chrome://version -> Command Line
# Use: https://www.google.com/intl/zh-CN/inputtools/chrome/
- name: Native Wayland for Chrome (unsupported chinese input method)
  block:

    # - name: Copy com.google.Chrome.desktop
    #   ansible.builtin.copy:
    #     src: ~/.local/share/flatpak/exports/share/applications/com.google.Chrome.desktop
    #     dest: ~/.local/share/applications/com.google.Chrome.desktop
    #     mode: "0644"

    # - name: Replace com.google.Chrome.desktop
    #   ansible.builtin.replace:
    #     path: ~/.local/share/applications/com.google.Chrome.desktop
    #     regexp: 'Exec=/usr/bin/flatpak run'
    #     replace: 'Exec=/usr/bin/flatpak run --socket=wayland'

    - name: Copy chrome-flags.conf
      ansible.builtin.copy:
        src: files/chrome-flags.conf
        dest: ~/.var/app/com.google.Chrome/config/chrome-flags.conf
        mode: "0644"

- name: Upgrade neovim
  ansible.builtin.shell: |
    rm -rf ~/.local/opt/nvim
    mv ~/.local/opt/nvim-linux64 ~/.local/opt/nvim
    ln -sf ~/.local/opt/nvim/bin/nvim ~/.local/bin/nvim
  changed_when: false
