---

# ----------------------------------------------------------------
# Install dependency packages
# ----------------------------------------------------------------
# Download & Install:
# ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages" --tags kernel-latest
# ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages" --tags kernel-closest
# - name: Download / Install Kernel packages
#   ansible.builtin.include_tasks: kernel.yml
#   tags:
#     - kernel-latest
#     - kernel-closest
#   delegate_to: localhost

# ----------------------------------------------------------------
# Programming Languages
# ----------------------------------------------------------------
# Download & Install:
# ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages" --tags lang
- name: Programming Languages packages (include lang)
  ansible.builtin.include_tasks: lang.yml
  tags:
    - lang

