---

# ansible.builtin.shell: Execute shell commands on targets
# ansible.builtin.command: Execute commands on targets
# ansible.builtin.script: After transferring the local script, run the script on the remote node

- name: Download released packages - {{ item.key }}
  tags: "{{ (packages.keys() | list) + tags_extend }}"
  # tags: "{{ (packages.keys() | list) + ([tags_prefix] | product(packages.keys()) | map('join') | list) + tags_extend }}"
  delegate_to: localhost
  block:

    # Template a file out to a target host
    - name: Generate downloader-{{ item.key }}
      ansible.builtin.template:
        src: downloader.j2
        dest: /tmp/downloader-{{ item.key }}
        mode: '0755'

    # Execute commands on targets
    - name: Execute downloader-{{ item.key }}
      ansible.builtin.command: /tmp/downloader-{{ item.key }}
      changed_when: false
