---
# ----------------------------------------------------------------
# Programming Languages
# ----------------------------------------------------------------
# Download & Install:
# ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages" --tags lang

# ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages task=download" --tags lang
- name: Download Programming Languages packages
  ansible.builtin.include_tasks: downloader.yml
  loop:
    - { key: "go", value: "{{ packages['go'] }}" }
    - { key: "node", value: "{{ packages['node'] }}" }
    - { key: "rust", value: "{{ packages['rust'] }}" }
    - { key: "zig", value: "{{ packages['zig'] }}" }
    # - { key: "deno", value: "{{ packages['deno'] }}" }
  vars:
    tags_extend: ['lang']
  when:
    - task != 'install'
    - ('lang' in ansible_run_tags)
  tags:
    - lang

# ansible-playbook ~/.ansible/unix.yml --extra-vars "role=packages task=install" --tags lang
- name: Install/Upgrade Programming Languages
  ansible.builtin.include_tasks: installer.yml
  loop:
    - { key: "go", value: "{{ packages['go'] }}" }
    - { key: "node", value: "{{ packages['node'] }}" }
    - { key: "rust", value: "{{ packages['rust'] }}" }
    - { key: "zig", value: "{{ packages['zig'] }}" }
    # - { key: "deno", value: "{{ packages['deno'] }}" }
  vars:
    tags_extend: ['lang']
  when:
    - task != 'download'
    - ('lang' in ansible_run_tags)
  tags:
    - lang
