# vim: set filetype=yaml.ansible:
---

tools:

  # sudo dnf repoquery --userinstalled -q --qf '%{name}\n'
  dnf:
    - coreutils
    - util-linux
    - binutils
    - git
    - tig
    - zsh
    - tmux
    - neovim
    - curl
    - wget
    - grpcurl
    - telnet
    - mtr
    - nmap
    - nmap-ncat
    - lsof
    - file
    - entr  # Run arbitrary commands when files change
    - fastfetch
    - lshw
    - wl-clipboard
    - clang
    - android-tools
    - java-21-openjdk-devel
    - xlsclients  # list x11 client applications running on a display
    - ImageMagick
    - ffmpeg
    - chafa  # terminal graphics
    - fzf  # go
    - duf  # go: disk
    - gojq  # pure Go implementation of jq
    - gops
    - hyperfine  # rust: A command-line benchmarking tool
    - git-delta  # rust: git diff
    - difftastic  # rust: git diff
    - dua-cli  # rust: disk
    - bat  # rust: bat replacement for cat
    - fd-find  # rust: fd replacement for find
    - ripgrep  # rust: rg replacement for grep
    - zoxide  # rust: z/zi replacement for cd
    - tree-sitter-cli  # rust: tree-sitter
    - tealdeer  # rust: tldr
    - procs  # rust: procs replacement for ps
    - flatpak
    - draw.io  # [No official flatpak version](https://github.com/jgraph/drawio-desktop/issues/1834#issuecomment-2317783404)
    - firewall-config  # firewalld gui

  flatpak:
    - dconf-editor
    - com.github.tchx84.Flatseal
    - com.qq.QQ
    - com.tencent.WeChat
    - com.baidu.NetDisk
    - com.google.Chrome
    - io.podman_desktop.PodmanDesktop
    - com.github.phase1geo.minder
    - io.gitlab.news_flash.NewsFlash
    - org.inkscape.Inkscape
    - org.shotcut.Shotcut

    # NOTE: Drawio installed with flatpak cannot input Chinese
    # - com.jgraph.drawio.desktop

  go:
    - github.com/ivaaaan/smug@latest  # tmux session manager
    - github.com/arl/gitmux@latest  # git status on tmux line
    - github.com/jesseduffield/lazygit@latest  # dnf copr enable atim/lazygit
    - github.com/antonmedv/fx@latest  # terminal JSON viewer
    - go install github.com/mikefarah/yq/v4@latest  # YAML, JSON, XML, CSV, TOML and properties processor
    - github.com/charmbracelet/glow@latest  # terminal markdown viewer
    - github.com/boyter/scc@latest  # such as tokei based on rust
    - github.com/mattn/goreman@latest  # manage Procfile-based applications
    - github.com/traefik/yaegi/cmd/yaegi@latest  # repl

    - github.com/bykof/go-plantuml@latest
    - github.com/ofabry/go-callvis@latest  # call graph
    - golang.org/x/tools/cmd/callgraph@latest
    - golang.org/x/tools/cmd/digraph@latest

    - github.com/spf13/cobra-cli@latest
    - github.com/mccutchen/go-httpbin/v2/cmd/go-httpbin@latest

    - github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    - -tags 'postgres mysql sqlite3' github.com/xo/usql@latest

  rust:  # cargo
    - bottom  # btm process/system monitor, dnf copr enable atim/bottom
    - websocat  # dnf copr enable atim/websocat
    - gping  # dnf copr enable atim/gping
    - bandwhich  # dnf copr enable atim/bandwhich
    - netscanner  # network scanner & diagnostic tool
    - trippy  # A network diagnostic tool
    - fselect  # find files with SQL-like queries
    - cargo-depgraph
    - mdbook
    - mdbook-plantuml
    - mdbook-mermaid
    - mdbook-toc
    - mdbook-pagetoc

  python:  # pip
    - ipython
    - ddgr  # DuckDuckGo from the terminal
    - yt-dlp
    - spotdl
    - edir  # rename, remove, and copy files and directories using your editor
    - mycli  # mycli -h 127.0.0.1 -uroot

  node:  # pnpm
    - tsx
    - npm-check-updates  # ncu
    - vite
