# vim: set filetype=yaml.ansible:
---

tools:

  # sudo dnf history userinstalled
  dnf:
    - git
    - zsh
    - util-linux-user
    - tmux
    - neovim
    - binutils
    - clang
    - curl
    - wget
    - telnet
    - file
    - entr  # Run arbitrary commands when files change
    - fastfetch
    - jq
    - wl-clipboard
    - flatpak
    - xlsclients  # list x11 client applications running on a display
    - android-tools
    - tig
    - git-lfs
    - ffmpeg
    - alsa-lib-devel  # sniffnet
    - libpcap-devel  # sniffnet
    - lshw
    # sudo dnf --setopt=install_weak_deps=False install tinygo
    - binaryen
    - llvm-devel
    - lld-libs
    - lld
    - glibc
    - libgcc
    - libstdc++
    - lld
    - llvm-libs

  # flatpak --user list --app --help
  # flatpak list --columns=application,runtime,version,size
  flatpak:
    - com.google.Chrome
    - io.podman_desktop.PodmanDesktop
    - com.github.phase1geo.minder
    - com.qq.QQ

    # NOTE: Drawio installed with flatpak cannot input Chinese
    # - com.jgraph.drawio.desktop

  go:
    - github.com/junegunn/fzf@latest
    - github.com/arl/gitmux@latest  # git status on tmux line
    - github.com/google/gops@latest
    - github.com/boyter/scc@latest
    - github.com/jesseduffield/lazygit@latest
    - github.com/muesli/duf@latest
    - github.com/itchyny/gojq/cmd/gojq@latest
    - github.com/antonmedv/fx@latest  # JSON viewer
    - github.com/charmbracelet/glow@latest  # markdown viewer
    - github.com/ivaaaan/smug@latest  # tmux session manager
    - github.com/traefik/yaegi/cmd/yaegi@latest  # repl

    - github.com/bykof/go-plantuml@latest
    - github.com/ofabry/go-callvis@master  # call graph
    - golang.org/x/tools/cmd/callgraph@master
    - golang.org/x/tools/cmd/digraph@master

    - golang.org/x/mobile/cmd/gomobile@latest
    - golang.org/x/mobile/cmd/gobind@latest

    - github.com/google/wire/cmd/wire@latest
    - github.com/envoyproxy/protoc-gen-validate@latest
    - google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    - github.com/go-kratos/kratos/cmd/kratos/v2@latest
    - github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest
    - github.com/google/gnostic/cmd/protoc-gen-openapi@latest

    - github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    - github.com/spf13/cobra-cli@latest
    - github.com/mattn/goreman@latest
    - github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
    - github.com/mccutchen/go-httpbin/v2/cmd/go-httpbin@latest

    # go tools for vscode
    - github.com/cweill/gotests/gotests@v1.6.0
    - github.com/fatih/gomodifytags@latest
    - github.com/josharian/impl@latest
    - github.com/haya14busa/goplay/cmd/goplay@v1.0.0
    - github.com/go-delve/delve/cmd/dlv@latest
    - honnef.co/go/tools/cmd/staticcheck@latest
    - golang.org/x/tools/gopls@latest

  rust:
    - bat
    - git-delta
    - difftastic
    - fd-find
    - ripgrep
    - zoxide
    - tealdeer
    - bottom
    - bandwhich
    - procs
    - dua-cli
    - cargo-nextest --locked
    - sniffnet
    - wasm-pack
    - cargo-depgraph
    - fnm

  python:
    - ipython
    - ddgr  # DuckDuckGo from the terminal
    # yt-dlp --proxy socks5://127.0.0.1:1080/ -f '(bestvideo+bestaudio/best)[protocol^=http]' --audio-quality 0 --cookies-from-browser chrome:~/.var/app/com.google.Chrome/ -o '/tmp/%(title)s.%(ext)s' 'https://domain.com/some/uri'
    - yt-dlp
    - spotdl
    - secretstorage
    - edir  # rename, remove, and copy files and directories using your editor

  node:
    - pnpm
    - tsx
    - npm-check-updates  # ncu
    - eslint
