---

# ----------------------------------------------------------------
# dotfiles
# ----------------------------------------------------------------
- name: Check if dotfiles exists
  ansible.builtin.stat:
    path: "$HOME/.dotfiles"
  register: basic_dotfiles_check

- name: Clone dotfiles
  when: not basic_dotfiles_check.stat.exists
  # noqa command-instead-of-module
  ansible.builtin.shell: |
    # git config --global http.version HTTP/1.1
    git clone --bare https://github.com/ueaner/dotfiles.git "$HOME/.dotfiles"
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" checkout
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" config --local status.showUntrackedFiles no
  changed_when: false

# ----------------------------------------------------------------
# dotlocal
# ----------------------------------------------------------------
- name: Check if dotlocal exists
  ansible.builtin.stat:
    path: "$HOME/.dotlocal"
  register: basic_dotlocal_check

- name: Clone dotlocal
  when: not basic_dotlocal_check.stat.exists
  # noqa command-instead-of-module
  ansible.builtin.shell: |
    # git config --global http.version HTTP/1.1
    git clone --bare https://github.com/ueaner/local.git "$HOME/.dotlocal"
    git --git-dir="$HOME/.dotlocal" --work-tree="$HOME/.local" checkout
    git --git-dir="$HOME/.dotlocal" --work-tree="$HOME/.local" config --local status.showUntrackedFiles no
  changed_when: false
