---

# NOTE: For multiple same as hardware models, the code here needs further refinement.
# [Model Identifier]: https://support.apple.com/en-us/108052
#
# bash4+: brew install bash
# declare -A products=(
#     ["MacBookPro12,1"]=mac15
#     ["MacBookPro11,1"]=mac14
#     ["Link"]=cb13
# )
# ${products[$product]}
- name: Set the hostname in the LAN
  ansible.builtin.shell: |
    set -o pipefail
    hostname="{{ hostnames[ansible_product_name] }}"

    if [[ -f /sys/devices/virtual/dmi/id/product_name ]]; then
        product=$(cat /sys/devices/virtual/dmi/id/product_name)
        name=$(hostname)

        # xremap and sway/config include host-specific configs
        if [[ "$name" != "$hostname" ]]; then
          echo "set hostname to $hostname"
          sudo hostnamectl set-hostname --static "$hostname"
        fi

    elif [[ "$(uname -s)" == "Darwin" ]]; then
        product=$(sysctl -n hw.model)
        name=$(scutil --get ComputerName)

        if [[ "$name" != "$hostname" ]]; then
          echo "set hostname to $hostname"
          sudo scutil --set ComputerName "$hostname"
          sudo scutil --set LocalHostName "$hostname"
          sudo scutil --set HostName "$hostname"
        fi
    fi

    echo "hostname: $(hostname)"
  args:
    executable: bash
  changed_when: false
