---

- name: Fix too many open files - fs.inotify
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    if [[ ! -f /usr/lib/sysctl.d/00-inotify.conf ]]; then
        printf "user.max_inotify_instances = 1024\nuser.max_inotify_watches = 65536\n" | sudo tee /usr/lib/sysctl.d/00-inotify.conf
        sudo sysctl -p /usr/lib/sysctl.d/00-inotify.conf
    fi
  changed_when: false
