# Prelude
---

# ----------------------------------------------------------------
# done
# ----------------------------------------------------------------
- name: Check if play done
  ansible.builtin.stat:
    path: "~/.cache/endplay.all"
  register: prelude_done_check

- name: Welcome when play done
  when: prelude_done_check.stat.exists
  ansible.builtin.debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: If play done, end play
  when: prelude_done_check.stat.exists
  ansible.builtin.meta: end_play

# ----------------------------------------------------------------
# dotfiles
# ----------------------------------------------------------------
- name: Clone dotfiles (include dotfiles)
  ansible.builtin.include_tasks: dotfiles.yml

# ----------------------------------------------------------------
# os-release
# ----------------------------------------------------------------
- name: Setting the facts (include os-release)
  ansible.builtin.include_tasks: os-release.yml

# ----------------------------------------------------------------
# sudo without password
# ----------------------------------------------------------------
- name: Sudo without password (include sudo)
  ansible.builtin.include_tasks: sudo.yml

# ----------------------------------------------------------------
# fs.inotify: too many open files
# ----------------------------------------------------------------
- name: Fix too many open files (include inotify)
  when: ansible_system == "Linux"
  ansible.builtin.include_tasks: inotify.yml

# ----------------------------------------------------------------
# /usr/local/bin permissions
# ----------------------------------------------------------------
- name: Change the owner of the /usr/local/bin directory to {{ ansible_env.USER }}
  ansible.builtin.include_tasks: bin.yml

# ----------------------------------------------------------------
# Lets normal users use evdev and uinput without sudo
# ----------------------------------------------------------------
- name: Lets normal users use evdev and uinput without sudo (include uinput)
  when: ansible_system == "Linux"
  ansible.builtin.include_tasks: uinput.yml


# ----------------------------------------------------------------
# hostname
# ----------------------------------------------------------------
- name: Set the hostname of the Linux host in the LAN (include hostname)
  when:
    - ansible_system == "Linux"
    - inventory_hostname in groups['lan'] or inventory_hostname == "localhost"
    # - inventory_hostname != ansible_hostname
  ansible.builtin.include_tasks: hostname.yml

# ----------------------------------------------------------------
# Package Manager
# ----------------------------------------------------------------
- name: Configure Package Manager (include packager)
  ansible.builtin.include_tasks: packager.yml
