---

- name: Detect desktop name
  ansible.builtin.shell: |
    set -o pipefail
    {{ desktop_command }}
  changed_when: false
  # noqa var-naming[no-role-prefix]
  register: desktop

- name: Setting the facts
  ansible.builtin.set_fact:
    # noqa var-naming[no-role-prefix]
    desktop: "{{ desktop.stdout }}"

- name: DEBUG desktop
  ansible.builtin.debug:
    msg: "desktop is '{{ desktop }}'."
