---

- name: Allow user to use sudo without password
  ansible.builtin.shell: |
    set -o pipefail
    # Check if user has sudo NOPASSWD
    if ! sudo -n true 2>/dev/null; then
        # Allow user to use sudo without password
        echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/$USER"
    fi
  changed_when: false
