---

- name: Check if the wireless driver (wl) is installed
  ansible.builtin.shell: lsmod | grep wl
  changed_when: false
  ignore_errors: true
  register: system_wl_check
- name: DEBUG wireless driver (wl) is installed
  ansible.builtin.debug:
    var: system_wl_check.stdout_lines

- name: Install the broadcom wireless driver, and reboot
  when: system_wl_check is failed
  block:

    - name: Install the broadcom wireless packages
      become: true
      ansible.builtin.dnf:
        name:
          - akmods
          - broadcom-wl

    - name: Run akmods
      ansible.builtin.command: sudo akmods
      changed_when: false

    # Wait for reboot to complete when operating remotely
    - name: Reboot host and wait for it to restart (by include_tasks)
      ansible.builtin.include_tasks: reboot.yml


- name: Check if the wireless driver (wl) is installed after reboot
  ansible.builtin.shell: lsmod | grep wl
  changed_when: false
  ignore_errors: true
  register: system_wl_check
- name: DEBUG wireless driver (wl) is installed, again
  ansible.builtin.debug:
    var: system_wl_check.stdout_lines

- name: DEBUG wireless driver (wl) is installed, again, rc
  ansible.builtin.debug:
    var: system_wl_check.rc
