---

- name: Check if the wireless driver (wl) is installed
  ansible.builtin.shell: lsmod | grep wl
  changed_when: false
  ignore_errors: true
  register: wl_check
- ansible.builtin.debug: var=wl_check.stdout_lines

- name: Install the broadcom wireless driver, and reboot
  when: wl_check is failed
  block:

    - name: Install the broadcom wireless packages
      become: true
      become_method: sudo
      ansible.builtin.dnf:
        name:
          - akmods
          - broadcom-wl

    - name: Run akmods
      ansible.builtin.command: sudo akmods
      changed_when: false

    # Wait for reboot to complete when operating remotely
    - ansible.builtin.include_tasks: reboot.yml


- name: Check if the wireless driver (wl) is installed after reboot
  ansible.builtin.shell: lsmod | grep wl
  changed_when: false
  ignore_errors: true
  register: wl_check
- ansible.builtin.debug: var=wl_check.stdout_lines

- name: Install the wireless driver packages
  ansible.builtin.debug: var=wl_check.rc
