---

- name: Create kernel directory
  ansible.builtin.file:
    path: ~/kernel-{{ versions.kernel }}
    state: directory
    mode: '0755'

# - name: download kernel-headers package
#   shell:
#     url="https://kojipkgs.fedoraproject.org/packages/kernel-headers/{{versions.kernel_slash}}/{{item}}-{{versions.kernel}}.rpm";
#     dir_prefix="~/kernel-{{versions.kernel}}";
#     wget -c -P "$dir_prefix" "$url"
#   loop:
#   - kernel-headers

- name: Download kernel-headers package
  ansible.builtin.get_url:
    url: "https://kojipkgs.fedoraproject.org/packages/kernel-headers/{{ versions.kernel_slash }}/{{ item }}-{{ versions.kernel }}.rpm"
    dest: "~/kernel-{{ versions.kernel }}/{{ item }}-{{ versions.kernel }}.rpm"
    mode: "0644"
  loop:
    - kernel-headers

- name: Download kernel packages
  ansible.builtin.get_url:
    url: "https://kojipkgs.fedoraproject.org/packages/kernel/{{ versions.kernel_slash }}/{{ item }}-{{ versions.kernel }}.rpm"
    dest: "~/kernel-{{ versions.kernel }}/{{ item }}-{{ versions.kernel }}.rpm"
    mode: "0644"
  loop:
    - kernel
    - kernel-core
    - kernel-devel
    - kernel-devel-matched
    - kernel-modules
    - kernel-modules-core
    - kernel-modules-extra
    - kernel-modules-internal
    - kernel-uki-virt

- name: Install kernel & kernel-headers packages
  ansible.builtin.shell:
    sudo dnf install ~/kernel-{{ versions.kernel }}/kernel*.rpm
  changed_when: false

- name: DEBUG Kernel version before reboot the system
  ansible.builtin.debug:
    var: ansible_kernel

# Wait for reboot to complete when operating remotely
- name: Reboot host and wait for it to restart (by include_tasks)
  ansible.builtin.include_tasks: reboot.yml

- name: DEBUG Kernel version after reboot the system
  ansible.builtin.debug:
    var: ansible_kernel
