- name: "Change kernel version to {{ versions.kernel }}"
  ansible.builtin.include_tasks: kernel.yml
  when:
    - ansible_kernel != versions.kernel
    - ansible_product_name.startswith('MacBook')

- name: Install the broadcom wireless driver under MacBook (include broadcom-wl)
  ansible.builtin.include_tasks: broadcom-wl.yml
  when: "ansible_product_name.startswith('MacBook')"

- name: Run gsettings script (include gsettings)
  ansible.builtin.include_tasks: gsettings.yml
  when: ansible_distribution == "Fedora"
