---

- name: "Change kernel version to {{ versions.kernel }}"
  ansible.builtin.include_tasks: kernel.yml
  when:
    - ansible_kernel != versions.kernel
    - ansible_product_name.startswith('MacBook')

- name: Install the broadcom wireless driver under MacBook (include broadcom-wl)
  ansible.builtin.include_tasks: broadcom-wl.yml
  when: "ansible_product_name.startswith('MacBook')"

- name: Run gsettings script (include gsettings)
  ansible.builtin.include_tasks: gsettings.yml
  when: ansible_distribution == "Fedora"

# sudo dnf update --exclude="kernel*"
- name: Upgrade all packages, excluding kernel (dnf)
  become: true
  when: ansible_pkg_mgr == "dnf"
  ansible.builtin.dnf:
    name: "*"
    state: latest  # noqa package-latest
    exclude: 'kernel*'
  tags:
    - upgrade

- name: Fix too many open files - fs.inotify
  when: ansible_pkg_mgr == "dnf"
  ansible.builtin.shell: |
    set -o pipefail
    echo 'fs.inotify.max_user_instances=1024' | sudo tee /etc/sysctl.d/local.conf
    sudo sysctl -p /etc/sysctl.d/local.conf
  changed_when: false
