# GUI应用在操作行为上可分为最基本的两个部分 Normal（普通区） Insert（编辑区）
# - Normal 普通区部分（如Tab标签、内容展示等）通常的操作行为是：滚屏、查找界面关键字、复制界面内容等
#   - 使用 xremap 围绕 Super 键构建系统基础操作快捷键，统一和 macOS 一样的操作习惯
#   - 平衡 Ctrl 和 Super 的关系，划分二者的功能范畴，使系统基础操作快捷键和 Emacs 风格/终端快捷键可以并存
#   -   如 Ctrl+A 跳至行首，Super+A 全选; Ctrl+C 中断信号，Super+C 复制等
#   -   而非同样的功能有的地方使用 Ctrl+... 有的地方使用 Ctrl+Shift+...
#   - 基于此非苹果键盘，需要按苹果键位调整下
# - Insert 编辑区部分（如地址栏、文本框等）通常的操作行为是：移动光标、编辑输入框内容等
#   - 使用 gsttings gtk-key-theme=Emacs (readline) 操作风格，处理输入部分，保持和终端一样的操作习惯
#   - TODO Ctrl-u 的行为应为从光标处删除到行首，而非删除整行
#   - xremap 直接键映射 Ctrl 开头的快捷键，需要考虑是否会影响 gtk-key-theme=Emacs 和 vim 的编辑滚屏等操作
# 需要安装 GNOME Shell extension for xremap https://github.com/xremap/xremap-gnome
# busctl --user call org.gnome.Shell /com/k0kubun/Xremap com.k0kubun.Xremap WMClass
keymap:
- name: basic
  # 按键精确匹配的概念，默认 exact_match: false, 映射一个快捷键会扇出多个快捷键
  # 如映射了 Super-n: down
  #   按下 Super-Shift-n 会触发 Shift-down
  #   按下 Super-Control-n 会触发 Control-down
  # 很可能稍不留神就拦截到系统定义的快捷键
  # 使用精确匹配，只拦截显式定义的快捷键
  exact_match: true
  application:
    # tmux 的快捷键配合 alacritty 进行定义
    not: Alacritty
  remap:
    # Super-tab switch applications
    #  Ctrl-tab switch tabs
    #  Super-`  当前选中的应用窗口间切换
    # Window / Tab
    Super-n: C-n              # new window
    Super-t: C-t              # new tab
    Super-w: [Esc, C-w]       # close tab
    Super-Shift-t: C-Shift-t  # 重新打开刚关闭的标签页
    # Editting
    Super-z: C-z              # undo
    Super-Shift-z: C-Shift-z  # redo
    Super-x: C-x              # Cut
    Super-c: C-c              # Copy
    Super-v: C-v              # Paste
    Super-f: C-f              # find
    Super-g: C-g              # find next
    Super-Shift-g: C-Shift-g  # find previous
    Super-l: [Esc, C-l]       # Location Bar / Select Line
    # C-a 会覆盖 GNOME gtk-key-theme=Emacs 跳转到行首的动作，使用 C-/ 代替 C-a 触发全选
    # / 特殊字符使用 KEY_XXX 的形式定义
    # https://github.com/k0kubun/xremap#keymap
    # https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L78
    Super-a: C-KEY_SLASH      # Select All
    Super-o: C-o              # open options or open choose file dialog
    Super-p: C-p              # print
    Super-s: C-s              # save
    #Ctrl-u: [Shift-Home, Backspace]       # Emacs C-u
