# ----------------------------------------------------------------
# Golang, Install/Upgrade
# ----------------------------------------------------------------

---

- name: Install/Upgrade Go
  install-package:
    name: go
    placeholders:
      version: curl -s 'https://golang.google.cn/VERSION?m=text' | head -n1
    archives:
      # https://dl.google.com/go/go1.25.0.linux-arm64.tar.gz
      - https://dl.google.com/go/<version>.linux-amd64.tar.gz
      - https://dl.google.com/go/<version>.linux-arm64.tar.gz
      - https://dl.google.com/go/<version>.darwin-amd64.tar.gz
      - https://dl.google.com/go/<version>.darwin-arm64.tar.gz
    strip: 1
    dst: $XDG_DATA_HOME/go # defaults to $XDG_BIN_HOME
    postinstall: |-
      # ln -sf $XDG_DATA_HOME/go/bin/* $XDG_BIN_HOME
      curl --create-dirs -L -o ~/.local/share/zsh/site-functions/_golang \
          ${GITHUB_PROXY}https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_golang
      go version
  tags:
    - go
