# ----------------------------------------------------------------
# Node.js, Bun, Deno Install/Upgrade
# ----------------------------------------------------------------

---

- name: Install/Upgrade Node.js
  install-package:
    name: node
    placeholders:
      version: curl -s -L https://nodejs.org/download/release/index.json | jq -r '[.[] | select(.lts!=false)] | sort_by(.lts, .version) | reverse | .[0].version'
    archives:
      # https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz
      # https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-x64.tar.xz
      - https://nodejs.org/dist/<version>/node-<version>-linux-x64.tar.xz
      - https://nodejs.org/dist/<version>/node-<version>-linux-arm64.tar.xz
      - https://nodejs.org/dist/<version>/node-<version>-darwin-x64.tar.xz
      - https://nodejs.org/dist/<version>/node-<version>-darwin-arm64.tar.xz
    strip: 1
    dst: $XDG_DATA_HOME/node # defaults to $XDG_BIN_HOME
    postinstall: |-
      ln -sf $XDG_DATA_HOME/node/bin/* $XDG_BIN_HOME

      curl -fsSL https://get.pnpm.io/install.sh | sh -
      $XDG_DATA_HOME/pnpm/pnpm config set global-bin-dir ~/.local/bin
      $XDG_DATA_HOME/pnpm/pnpm completion zsh > ~/.local/share/zsh/site-functions/_pnpm

      curl --create-dirs -L -o ~/.local/share/zsh/site-functions/_node \
          ${GITHUB_PROXY}https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_node
      node --version
  tags:
    - nodejs
    - node
    - pnpm


# FIXME on cb13:
# $ file ~/.local/bin/bun
# ~/.local/bin/bun: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=cae47aa962a9a70f6d2a46c863ec4b4568cdd92e, not stripped
# $ ~/.local/bin/bun --version
# zsh: illegal hardware instruction (core dumped)  ~/.local/bin/bun --version
- name: Install/Upgrade bun
  when: ansible_hostname != "cb13"
  install-package:
    name: bun
    placeholders:
      repo: oven-sh/bun
    template: "{{ template.github.latest }}"
    archives:
      - bun-linux-x64.zip
      - bun-linux-aarch64.zip
      - bun-darwin-x64.zip
      - bun-darwin-aarch64.zip
    dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
    strip: 1
    include:
      - bun
    postinstall: |-
      chmod +x ~/.local/bin/bun
      bun completions > ~/.local/share/zsh/site-functions/_bun
      bun --version
  tags:
    - bun

- name: Install/Upgrade bun (For Intel CPUs before 2013)
  when: ansible_hostname == "cb13"
  install-package:
    name: bun
    placeholders:
      repo: oven-sh/bun
    template: "{{ template.github.latest }}"
    archives:
      # - https://github.com/oven-sh/bun/releases/download/bun-v1.2.21/bun-linux-x64-baseline.zip
      - bun-linux-x64-baseline.zip
      - bun-darwin-x64-baseline.zip
    dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
    strip: 1
    include:
      - bun
    postinstall: |-
      chmod +x ~/.local/bin/bun
      bun completions > ~/.local/share/zsh/site-functions/_bun
      bun --version
  tags:
    - bun

- name: Install/Upgrade Deno
  install-package:
    name: deno
    placeholders:
      repo: denoland/deno
    template: "{{ template.github.latest }}"
    archives:
      # https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip
      - deno-x86_64-unknown-linux-gnu.zip
      - deno-aarch64-unknown-linux-gnu.zip
      - deno-x86_64-apple-darwin.zip
      - deno-aarch64-apple-darwin.zip
    dst: $XDG_BIN_HOME # defaults to $XDG_BIN_HOME
    include:
      - deno
    postinstall: |-
      chmod +x ~/.local/bin/deno
      deno completions zsh > ~/.local/share/zsh/site-functions/_deno
      deno --version
  tags:
    - deno
