# ----------------------------------------------------------------
# Rust, Install/Upgrade
# ----------------------------------------------------------------

---

# https://developer.fedoraproject.org/tech/languages/rust/rust-installation.html
- name: Install/Upgrade Rust
  install-package:
    name: rust
    # https://static.rust-lang.org/dist/rust-1.84.1-x86_64-unknown-linux-gnu.tar.xz
    install: |-
      export CARGO_HOME=$XDG_DATA_HOME/cargo
      export RUSTUP_HOME=$XDG_DATA_HOME/rustup

      if [[ ! -x $CARGO_HOME/bin/rustc ]]; then
          curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y
          $CARGO_HOME/bin/rustup default stable
      else
          rustup self update
          rustup update
      fi
      $CARGO_HOME/bin/rustc --version

      # error: no default toolchain is configured
      ln -sf $XDG_DATA_HOME/cargo/bin/* $XDG_BIN_HOME
      ln -sf $XDG_DATA_HOME/rustup/toolchains/$(rustup default | cut -d ' ' -f1)/share/zsh/site-functions/_cargo \
          ~/.local/share/zsh/site-functions/_cargo
      rustup completions zsh > ~/.local/share/zsh/site-functions/_rustup
      rustc --version
  tags:
    - rust
