# ----------------------------------------------------------------
# Zig, Install/Upgrade
# ----------------------------------------------------------------

---

- name: Install/Upgrade Zig
  install-package:
    name: zig
    placeholders:
      version: curl -s -L https://ziglang.org/download/index.json | jq -r 'del(.master) | keys_unsorted | first'
    archives:
      # https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz
      - https://ziglang.org/download/<version>/zig-x86_64-linux-<version>.tar.xz
      - https://ziglang.org/download/<version>/zig-aarch64-linux-<version>.tar.xz
      - https://ziglang.org/download/<version>/zig-x86_64-macos-<version>.tar.xz
      - https://ziglang.org/download/<version>/zig-aarch64-macos-<version>.tar.xz
    strip: 1
    dst: $XDG_DATA_HOME/zig # defaults to $XDG_BIN_HOME
    postinstall: |-
      ln -sf $XDG_DATA_HOME/zig/zig $XDG_BIN_HOME
      curl --create-dirs -L -o ~/.local/share/zsh/site-functions/_zig \
          ${GITHUB_PROXY}https://raw.githubusercontent.com/ziglang/shell-completions/master/_zig
      zig version
  tags:
    - zig
