version: "3"

vars:
  # 定义 List[Map]
  SECTIONS:
    - { name: "prelude", desc: "(0) 系统初始化 (点文件、主机名及包管理器底座)" }
    - { name: "desktop", desc: "(1) 桌面环境" }
    - { name: "app", desc: "(2) 应用程序" }
    - { name: "service", desc: "(3) 服务配置" }
    - { name: "terminal", desc: "(4) 终端环境" }
    - { name: "lang", desc: "(5) 开发工具" }
    - { name: "all", desc: "以上全部 Section" }

tasks:
  default:
    cmds:
      - task: ui

  ui:
    desc: "交互式任务运行"
    internal: true # <--- 内部方法，不现在 task --list-all 列表中
    interactive: true # <--- 交互式 task
    silent: true # <--- 隐藏所有命令回显，只看结果
    # POSIX 规范：被信号中断的进程返回码是 128 + 信号编号。由于 SIGINT 是 2，所以按下 Esc 后 fzf 退出并抛出 130
    # ignore_error: true # <--- 防止 Esc 退出(130)时 Task 报错，或使用 fzf ... || true
    vars:
      # 格式化 SECTIONS 为: "name | desc" 形式供 fzf 展现
      OPTIONS:
        sh: |
          {{range .SECTIONS -}}
          echo "{{.name}} : {{.desc}}";
          {{- end}}
    cmds:
      - |-
        # 1. 提取 Section 和描述 2. 模糊搜索 3. 截取 Section 名并执行
        SELECTED_SECTIONS=$(echo "{{.OPTIONS}}" | column -t -s ':' | fzf --multi || true)

        if [[ -n "$SELECTED_SECTIONS" ]]; then
          # 如果选择了 all，只执行 all，跳过其他 section
          if echo "$SELECTED_SECTIONS" | grep -q '^all '; then
            ./main all
          else
            echo "$SELECTED_SECTIONS" | awk '{print $1}' | xargs task process --
          fi
        fi

  process:
    desc: "一次执行多个 Section，如: task process -- <section1> <section2>"
    cmds:
      - for: { var: CLI_ARGS }
        task: run-section
        vars: { ITEM: "{{.ITEM}}" }

  run-section:
    silent: true
    internal: true
    cmds:
      - ./main {{.ITEM}}
