# Copy this file to ~/.var/app/com.google.Chrome/config/chrome-flags.conf
#
# Chrome 138+
#
# wayland:
#   --enable-features=WaylandWindowDecorations
#   --ozone-platform=wayland
#   --wayland-per-window-scaling
#
# two-finger back/forward navigation:
#   --enable-features=TouchpadOverscrollHistoryNavigation
#
# Chinese input method (chrome://flags/#wayland-text-input-v3 on Chrome 129+):
#   --enable-wayland-ime
#   --wayland-text-input-version=3
#
# Q: GNOME 48: It always asks to Add Keyboard Shortcuts
# A: --disable-features=GlobalShortcutsPortal
# See:
# https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/208
# https://issues.chromium.org/issues/404298968
#
# See https://github.com/fcitx/fcitx5/issues/263#issuecomment-2379702134
--ozone-platform=wayland
--wayland-per-window-scaling
--enable-wayland-ime
--wayland-text-input-version=3
--enable-features=TouchpadOverscrollHistoryNavigation,WaylandWindowDecorations,MemorySaverModeAggressive
--disable-features=GlobalShortcutsPortal
# GPU 全关, Figma 打不开
# --disable-gpu
# --disable-gpu-compositing
# --disable-software-rasterizer

# --enable-features=VaapiVideoDecoder   # 仅视频硬解，不碰 rasterization

# # --- 老核显容易卡死 ---
# --enable-zero-copy
# --enable-gpu-rasterization
# --ignore-gpu-blocklist

# # --- 内存优化 (核心策略) ---
# --enable-low-end-device-mode
# --process-per-site
# # 限制 JS 堆内存，对 Claude/Lark 这种重度应用很有效
# --max-old-space-size=1024

# # --- 性能与资源控制 ---
# --enable-gpu-rasterization
# --enable-zero-copy
# --force-gpu-mem-available-mb=256
# # 只有当 Chrome 窗口处于后台时，才限制渲染进程资源
# --disable-renderer-backgrounding
