---

- name: Configure GNOME Desktop Environment
  block:

    - name: Install gnome shell extensions
      delegate_to: localhost
      ansible.builtin.command: ~/bin/gnome-shell-extensions
      changed_when: false

    - name: Run gsettings script
      ansible.builtin.command: ~/bin/gnome-gsettings
      changed_when: false

    - name: Make gnome more lightweight
      ansible.builtin.command: ~/bin/gnome-lightweight
      changed_when: false
