---

- name: Detect desktop name
  ansible.builtin.shell: |
    if [[ "{{ ansible_facts.distribution }}" == "MacOSX" ]]; then
      echo "aqua"
    elif [[ "{{ ansible_facts.distribution }}" == "Fedora" ]]; then
      . /etc/os-release
      if [[ "${VARIANT_ID}" == "workstation" ]]; then
        echo "gnome"
      elif [[ "${VARIANT_ID}" == "sway" ]]; then
        echo "sway"
      fi
    fi
  changed_when: false
  # noqa var-naming[no-role-prefix]
  register: desktop_name

- name: Setting the facts
  ansible.builtin.set_fact:
    # noqa var-naming[no-role-prefix]
    desktop_name: "{{ desktop_name.stdout }}"

- name: DEBUG desktop_name
  ansible.builtin.debug:
    msg: "desktop_name is '{{ desktop_name }}'."
