---

- name: Configure Package Manager
  block:
    - name: Using the Tsinghua/USTC repositories for dnf
      ansible.builtin.script: ~/bin/dnf-util -m ustc -x -c
      changed_when: false

    - name: Using the SJTU mirror for flatpak
      # See: ~/.local/share/flatpak/repo/config
      # Flatpak package installations may fail while the mirror is syncing with the origin server.
      # Try running `curl -L -I https://dl.flathub.org/repo/config` locally to test.
      # https://mirrors.ustc.edu.cn/help/flathub.html
      ansible.builtin.shell: |
        set -o pipefail
        if ! flatpak remotes --user --columns=name,url | grep --quiet sjtu; then
            # curl -L https://mirror.sjtu.edu.cn/flathub/flathub.gpg -o /tmp/flathub.gpg
            # flatpak remote-modify --user --gpg-import=/tmp/flathub.gpg --url=https://mirror.sjtu.edu.cn/flathub flathub
            curl -L https://dl.flathub.org/repo/flathub.gpg -o /tmp/flathub.gpg
            flatpak remote-modify --user --gpg-import=/tmp/flathub.gpg --url=https://dl.flathub.org/repo flathub
            # flatpak remote-modify --url=https://mirrors.ustc.edu.cn/flathub flathub
        fi

        flatpak remotes --show-details
      changed_when: false

      # curl -L https://sdk.gnome.org/keys/gnome-sdk.gpg -o /tmp/gnome-sdk.gpg
      # flatpak remote-add --user --if-not-exists --gpg-import=/tmp/gnome-sdk.gpg gnome-apps https://sdk.gnome.org/repo-apps/

# Fedora 41+: ansible.builtin.dnf depends on python3-libdnf5
# See: https://github.com/ansible/ansible/issues/84206
- name: Ensure python3-libdnf5 is installed on Fedora 41+
  ansible.builtin.command: sudo dnf install -y python3-libdnf5
  changed_when: false
