---

# Fedora 41+ https://github.com/ansible/ansible/issues/84206
- name: Ensure python3-libdnf5 is installed on Fedora 41+
  ansible.builtin.command: sudo dnf install -y python3-libdnf5
  changed_when: false

- name: Configure Package Manager
  block:
    - name: Using the Tsinghua/USTC repositories for dnf
      ansible.builtin.command: ~/bin/dnf-repos ustc
      changed_when: false

    - name: Copy dnf.conf
      become: true
      ansible.builtin.copy:
        src: files/dnf.conf
        dest: /etc/dnf/dnf.conf
        mode: "0644"

    - name: Using the SJTU mirror for flatpak
      # ~/.local/share/flatpak/repo/config
      ansible.builtin.shell: |
        flatpak --user remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
        curl -L https://mirror.sjtu.edu.cn/flathub/flathub.gpg -o /tmp/flathub.gpg
        flatpak --user remote-modify --gpg-import=/tmp/flathub.gpg flathub
      changed_when: false
