# macOS-ish keyboard remap with xremap
---

# Install and start xremap service
# https://github.com/ueaner/dotfiles/blob/main/.config/systemd/user/xremap.service
# https://github.com/ueaner/dotfiles/tree/main/.config/autostart/xremap.desktop

- name: Check if xremap is installed
  ansible.builtin.stat:
    path: "~/.local/bin/xremap"
  register: basic_xremap_check

- name: Install xremap (GNOME Wayland)
  when:
    - not basic_xremap_check.stat.exists
    - desktop == "GNOME"
  ansible.builtin.unarchive:
    src: "{{ archives_server }}/xremap-linux-x86_64-gnome.zip"
    dest: "~/.local/bin/"
    remote_src: true
  notify: Start xremap service

- name: Install xremap (Sway)
  when:
    - not basic_xremap_check.stat.exists
    - desktop == "Sway"
  ansible.builtin.unarchive:
    # src: "{{ archives_server }}/xremap-linux-x86_64-wlroots.zip"
    src: "{{ archives_server }}/xremap-linux-x86_64-sway.zip"
    dest: "~/.local/bin/"
    remote_src: true
  notify: Start xremap service
