---

- name: Check if zsh is installed
  ansible.builtin.command: which zsh
  changed_when: false
  ignore_errors: true
  register: basic_zsh_check

- name: Install zsh if not present
  when: basic_zsh_check.rc != 0
  ansible.builtin.command: sudo dnf install -y zsh
  changed_when: false

- name: Set zsh as the default login shell for the current user
  when: "'/zsh' not in ansible_env.SHELL"
  ansible.builtin.command: chsh -s $(which zsh)
  changed_when: false
