---

# ----------------------------------------------------------------
# done
# ----------------------------------------------------------------
- name: ALL DONE
  ansible.builtin.file:
    path: "~/.cache/endplay.all"
    state: touch
    mode: "0644"

- name: WELCOME
  ansible.builtin.debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"
