# Prelude
---

# ----------------------------------------------------------------
# done
# ----------------------------------------------------------------
- name: Check if play done
  ansible.builtin.stat:
    path: "~/.cache/endplay.all"
  register: prelude_done_check

- name: Welcome when play done
  when: prelude_done_check.stat.exists
  ansible.builtin.debug:
    msg: "Welcome to {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: If play done, end play
  when: prelude_done_check.stat.exists
  ansible.builtin.meta: end_play

# ----------------------------------------------------------------
# dotfiles
# ----------------------------------------------------------------
- name: Clone dotfiles (include dotfiles)
  ansible.builtin.include_tasks: dotfiles.yml

# ----------------------------------------------------------------
# os-release
# ----------------------------------------------------------------
- name: Setting the facts (include os-release)
  ansible.builtin.include_tasks: os-release.yml

# ----------------------------------------------------------------
# sudo without password
# ----------------------------------------------------------------
- name: Sudo without password (include sudo)
  ansible.builtin.include_tasks: sudo.yml

# ----------------------------------------------------------------
# hostname
# ----------------------------------------------------------------
- name: Set hostname (include hostname)
  when:
    - ansible_system == "Linux"
    - inventory_hostname in groups['lan'] or inventory_hostname == "localhost"
    # - inventory_hostname != ansible_hostname
  ansible.builtin.include_tasks: hostname.yml
