# Terminal Environment
---

# ----------------------------------------------------------------
# nvim, installing nvim with dnf
# ----------------------------------------------------------------
#- name: Install/Upgrade neovim
#  ansible.builtin.include_tasks: neovim.yml

# ----------------------------------------------------------------
# alacritty.desktop for Sway
# ----------------------------------------------------------------
- name: Alacritty desktop entry add font.size option
  ansible.builtin.include_tasks: alacritty.yaml

# ----------------------------------------------------------------
# gitmux: git status in tmux status bar
# ----------------------------------------------------------------
- name: Install/Upgrade gitmux
  ansible.builtin.include_tasks: tmux.yml

# ----------------------------------------------------------------
# zsh
# ----------------------------------------------------------------
- name: Set zsh as the default login shell for the current user
  when: "'/zsh' not in ansible_env.SHELL"
  ansible.builtin.command: chsh -s $(which zsh)
  changed_when: false

# ----------------------------------------------------------------
# lazygit
# ----------------------------------------------------------------
- name: Install/Upgrade lazygit
  ansible.builtin.include_tasks: git.yml
  tags:
    - git

# ----------------------------------------------------------------
# tldr
# ----------------------------------------------------------------
- name: Install/Upgrade tldr python client (include_tasks)
  ansible.builtin.include_tasks: tldr.yml
  tags:
    - tldr
